export const conflictStrings = {
  en: {
    title: 'Conflict Intelligence',
    layers: 'Conflict layers',
    incidents: 'Incidents',
    unavailable: 'No governed geometry held',
    layerNames: ['Fronts', 'Displacement', 'Corridors', 'Infrastructure', 'Cessation', 'Spillover'],
    observations: 'Recent observations · chronological',
    evidence: 'Reviewed retained evidence',
    empty: 'Not assessed · no reviewed retained evidence is held.',
    notAssessed: 'Not assessed',
    unordered:
      'No upstream attention ranking is available. Observations are shown chronologically.',
    loading: 'Reading retained evidence…',
    error: 'Retained evidence is temporarily unavailable.',
    retry: 'Retry',
    back: 'Back to observations',
    map: 'Open full Map Intelligence',
    return: 'Return to Conflict Intelligence',
    publicationOnly: 'Publication date only · occurrence time not established',
    revisions: {
      LOCATION_CORRECTION: 'Location correction',
      CLASSIFICATION_CHANGE: 'Classification change',
      IMPACT_METADATA_CHANGE: 'Impact metadata change',
      SOURCE_REVISION: 'Source revision',
      RETRACTION: 'Retracted',
    },
    occurrence: 'Occurrence',
    actors: 'Actors · source names',
    provenance: 'Location provenance',
    precision: 'Location precision',
    revision: 'Revision',
    source: 'Source',
    acquired: 'Retained at',
    publisherTime: 'Publisher recorded at',
    geometryWithheld:
      'Geometry is not drawable here at its governed precision. No substitute location is shown.',
    scale: 'Publisher severity scale',
    records: 'reviewed retained records',
    retainedCount: 'retained',
    drawableCount: 'map-visible',
    withheldCount: 'coarser precision retained',
    observation: 'Retained conflict observation',
    eventClassification: 'Event classification',
    sourceEventId: 'Source event ID',
    sourceCountry: 'Source country',
    unclassifiedDetail:
      'No accepted event-type mapping is held for this retained record. The occurrence remains visible without inventing a class.',
    watch: 'Watch',
    ask: 'Ask AI',
    sheet: 'Conflict evidence',
    expand: 'Change sheet height',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    base: 'Reference geography · observation precision is stated with each record.',
    events: {
      ARMED_CLASH: 'Armed clash',
      EXPLOSION_REMOTE_VIOLENCE: 'Explosion / remote violence',
      VIOLENCE_AGAINST_CIVILIANS: 'Violence against civilians',
      SIEGE_OR_ENCIRCLEMENT: 'Siege / encirclement',
      AERIAL_OR_NAVAL_ACTION: 'Aerial / naval action',
      CEASEFIRE_VIOLATION: 'Ceasefire violation',
      EVENT_TYPE_NOT_CLASSIFIED: 'Event type not classified',
    },
  },
  pl: {
    title: 'Analiza konfliktów',
    layers: 'Warstwy konfliktów',
    incidents: 'Incydenty',
    unavailable: 'Brak zatwierdzonej geometrii',
    layerNames: [
      'Fronty',
      'Przesiedlenia',
      'Korytarze',
      'Infrastruktura',
      'Zawieszenie broni',
      'Skutki transgraniczne',
    ],
    observations: 'Ostatnie obserwacje · chronologicznie',
    evidence: 'Zachowane, zweryfikowane dane',
    empty: 'Nie oceniono · brak zachowanych, zweryfikowanych danych.',
    notAssessed: 'Nie oceniono',
    unordered:
      'Brak rankingu uwagi ze źródła nadrzędnego. Obserwacje są uporządkowane chronologicznie.',
    loading: 'Odczyt zachowanych danych…',
    error: 'Zachowane dane są chwilowo niedostępne.',
    retry: 'Ponów',
    back: 'Powrót do obserwacji',
    map: 'Otwórz pełną mapę',
    return: 'Powrót do analizy konfliktów',
    publicationOnly: 'Tylko data publikacji · czas zdarzenia nieustalony',
    revisions: {
      LOCATION_CORRECTION: 'Korekta lokalizacji',
      CLASSIFICATION_CHANGE: 'Zmiana klasyfikacji',
      IMPACT_METADATA_CHANGE: 'Zmiana danych o skutkach',
      SOURCE_REVISION: 'Wersja źródła',
      RETRACTION: 'Wycofano',
    },
    occurrence: 'Wystąpienie',
    actors: 'Uczestnicy · nazwy źródłowe',
    provenance: 'Pochodzenie lokalizacji',
    precision: 'Dokładność lokalizacji',
    revision: 'Wersja',
    source: 'Źródło',
    acquired: 'Zachowano',
    publisherTime: 'Zapis wydawcy',
    geometryWithheld:
      'Nie można pokazać geometrii z podaną dokładnością. Nie pokazano lokalizacji zastępczej.',
    scale: 'Skala dotkliwości wydawcy',
    records: 'zachowanych, zweryfikowanych rekordów',
    retainedCount: 'zachowane',
    drawableCount: 'widoczne na mapie',
    withheldCount: 'zachowane z mniejszą dokładnością',
    observation: 'Zachowana obserwacja konfliktu',
    eventClassification: 'Klasyfikacja zdarzenia',
    sourceEventId: 'Identyfikator zdarzenia źródłowego',
    sourceCountry: 'Kraj według źródła',
    unclassifiedDetail:
      'Brak zaakceptowanego mapowania typu zdarzenia dla tego rekordu. Zdarzenie pozostaje widoczne bez wymyślania klasy.',
    watch: 'Obserwowane',
    ask: 'Zapytaj AI',
    sheet: 'Dane o konfliktach',
    expand: 'Zmień wysokość panelu',
    zoomIn: 'Przybliż',
    zoomOut: 'Oddal',
    base: 'Geografia referencyjna · dokładność podano przy każdym rekordzie.',
    events: {
      ARMED_CLASH: 'Starcie zbrojne',
      EXPLOSION_REMOTE_VIOLENCE: 'Eksplozja / atak zdalny',
      VIOLENCE_AGAINST_CIVILIANS: 'Przemoc wobec ludności cywilnej',
      SIEGE_OR_ENCIRCLEMENT: 'Oblężenie / okrążenie',
      AERIAL_OR_NAVAL_ACTION: 'Działanie lotnicze / morskie',
      CEASEFIRE_VIOLATION: 'Naruszenie zawieszenia broni',
      EVENT_TYPE_NOT_CLASSIFIED: 'Typ zdarzenia niesklasyfikowany',
    },
  },
} as const;
