import type { FollowStrings } from './followStrings';

/**
 * REASON TO RETURN R1 — fr / de / es / pt / ar DRAFTS (Claude Code), pending Claude L
 * qualification. They exist so a reader of these locales is never shown English chrome (G12).
 * They carry the same meaning rules as EN: no urgency, an incomplete check is never "no change",
 * a missing report is never a retraction or a sign of safety.
 */
export const FR: FollowStrings = {
  follow: 'Suivre cette question',
  following: 'Suivie',
  followFailed: 'Non suivie. Rien n’a été modifié.',
  followNote: 'Enregistrée dans Mes mises à jour avec cette réponse comme point de départ. Rien ne s’exécute tant que vous ne vérifiez pas.',
  myUpdates: 'Mes mises à jour',
  myUpdatesIntro:
    'Les questions que vous suivez. Chaque vérification est lancée par vous ; Ask la compare à votre dernière réponse enregistrée et ne montre que ce que les sources confirment.',
  empty: 'Vous ne suivez encore aucune question. Utilisez « Suivre cette question » sur une réponse.',
  signedOut: 'Connectez-vous pour voir les questions que vous suivez.',
  unavailable: 'Les questions suivies ne sont pas disponibles pour le moment.',
  network: 'Impossible de joindre Ask. Vos questions suivies sont inchangées.',
  baseline: (asOf, age) => `Dernière réponse enregistrée : ${asOf} (${age})`,
  noBaseline: 'Aucune réponse enregistrée',
  lastChecked: (when) => `Dernière vérification : ${when}`,
  lastSuccessful: (when) => `Dernière vérification terminée : ${when}`,
  neverChecked: 'Pas encore vérifiée depuis le suivi',
  checkForChanges: 'Vérifier les changements',
  checkCost: 'Une vérification lance une nouvelle recherche et une réponse, et compte dans votre utilisation quotidienne.',
  checkTooSoon: (m) => `Vérifiée à l’instant. Nouvelle vérification possible dans environ ${m} min.`,
  paused: 'En pause',
  pause: 'Mettre en pause',
  resume: 'Reprendre',
  edit: 'Modifier',
  save: 'Enregistrer',
  cancel: 'Annuler',
  titleLabel: 'Nom',
  questionLabel: 'Question',
  editNote: 'Modifier la question démarre une nouvelle comparaison : la prochaine vérification devient le nouveau point de départ.',
  remove: 'Ne plus suivre',
  removeConfirm: 'Ne plus suivre cette question ? Ses réponses enregistrées et son historique de vérifications seront supprimés.',
  removed: 'Vous ne suivez plus cette question.',
  history: 'Réponses enregistrées',
  outcome: {
    INCOMPLETE_CHECK: 'Vérification incomplète',
    INSUFFICIENT_BASELINE: 'Nouveau point de départ enregistré',
    CORRECTION: 'Correction signalée',
    MATERIAL_CHANGE: 'Changement signalé',
    NEW_EVIDENCE: 'Nouveaux articles',
    UNCHANGED: 'Aucun nouvel article',
    NO_RELEVANT_UPDATE: 'Aucune mise à jour pertinente trouvée',
  },
  outcomeDetail: {
    INCOMPLETE_CHECK:
      'La recherche n’a pas pu aboutir : ce n’est donc pas un « rien n’a changé ». Votre dernière réponse enregistrée reste telle quelle.',
    INSUFFICIENT_BASELINE:
      'Il n’y avait pas de réponse sourcée à comparer (ou la question a été modifiée) : cette vérification devient le nouveau point de départ.',
    CORRECTION:
      'Une source a révisé l’un de ses enregistrements gouvernés, ou un article récent indique corriger des informations antérieures. Ouvrez-le pour voir ce qui a changé.',
    MATERIAL_CHANGE: 'Des articles publiés depuis votre dernière réponse enregistrée confirment les points ci-dessous.',
    NEW_EVIDENCE: 'De nouveaux articles ont été publiés depuis votre dernière réponse enregistrée. Ils sont listés ci-dessous.',
    UNCHANGED:
      'Les sources trouvées sont celles déjà utilisées par votre dernière réponse enregistrée. Une nouvelle formulation seule n’est pas considérée comme un changement.',
    NO_RELEVANT_UPDATE:
      'La recherche s’est terminée sans trouver de nouvel article pertinent. Cela ne signifie pas qu’il ne se passe rien.',
  },
  structuredNew: 'Nouveaux enregistrements gouvernés',
  structuredLate: 'Enregistrements ajoutés maintenant sur des dates antérieures',
  structuredLateNote: 'Admis après votre dernière réponse enregistrée mais datés avant. Non comptés comme un nouvel événement.',
  structuredRevised: 'Enregistrements révisés par leur source',
  structuredUnassessed: (classes) => `Données structurées non évaluées lors de cette vérification : ${classes}.`,
  structuredNotSeen: (n) => `Enregistrement(s) antérieur(s) non renvoyé(s) cette fois : ${n}. Ce n’est pas un retrait.`,
  structuredCarried: (n) => `Enregistrements inchangés depuis votre dernière réponse enregistrée : ${n}.`,
  partial: (sources) => `Certaines sources n’ont pas pu être vérifiées : ${sources}.`,
  newEvidence: 'Nouveaux articles',
  supportedChanges: 'Ce que confirment les nouveaux articles',
  possibleCorrections: 'Corrections signalées',
  correctionNote: 'Repéré d’après le titre ; Ask ne décide pas de ce qu’une correction remet en cause.',
  earlierFound: 'Articles antérieurs trouvés maintenant',
  earlierFoundNote: 'Publiés avant votre dernière réponse enregistrée. Affichés pour être complet, non comptés comme un changement.',
  notSeen: (n) => `${n} source(s) antérieure(s) non renvoyée(s) par cette recherche. Ce n’est pas un retrait.`,
  carriedOver: (n) => `Sources reprises de votre dernière réponse enregistrée : ${n}.`,
  expiredNotNote: 'L’expiration des avis officiels n’est pas évaluée.',
  checkBanner: (title, asOf) => `Vérification des changements pour « ${title} » depuis le ${asOf}.`,
  checkBannerHint: 'La question est prête ci-dessous. Rien ne s’exécute tant que vous ne l’envoyez pas.',
  checkRecording: 'Comparaison avec votre dernière réponse enregistrée…',
  checkRecorded: 'Vérification enregistrée dans Mes mises à jour.',
  checkNotRecorded: 'Cette réponse n’a pas été enregistrée comme vérification. Votre question suivie est inchangée.',
  checkPausedBanner: 'Cette question suivie est en pause. Reprenez-la dans Mes mises à jour pour la vérifier.',
  openMyUpdates: 'Ouvrir Mes mises à jour',
  ageDays: (n) => `il y a ${n} jour${n === 1 ? '' : 's'}`,
  ageHours: (n) => `il y a ${n} h`,
  ageJustNow: 'à l’instant',
  deleteConversation: 'Supprimer',
  deleteConversationConfirm: (title) => `Supprimer « ${title} » ? La conversation et ses réponses seront supprimées.`,
  deleteConversationNote: 'Les questions suivies sont conservées ; retirez-les dans Mes mises à jour.',
  deleteConversationBusy: 'Suppression…',
  deleteConversationFailed: 'Non supprimée. Réessayez.',
  conversationDeleted: 'Conversation supprimée.',
  searchingAll: 'Recherche dans toutes vos conversations…',
  nameLabel: 'Nom utilisé par Ask',
  nameHint: 'Facultatif. Ask ne tire jamais un nom de votre adresse e-mail. Laissez vide pour ne pas utiliser de nom.',
  nameSave: 'Enregistrer le nom',
  nameSaved: 'Nom enregistré.',
  nameCleared: 'Nom supprimé.',
  nameInvalid: 'Utilisez des lettres, espaces, apostrophes, traits d’union ou points — pas d’adresse e-mail ni de lien.',
  nameTooLong: '40 caractères au maximum.',
  nameFailed: 'Non enregistré. Votre nom est inchangé.',
  greeting: (name) => `Bon retour, ${name}.`,
};

export const DE: FollowStrings = {
  follow: 'Dieser Frage folgen',
  following: 'Gefolgt',
  followFailed: 'Nicht gefolgt. Es wurde nichts geändert.',
  followNote: 'In „Meine Updates“ gespeichert, mit dieser Antwort als Ausgangspunkt. Nichts läuft, bevor Sie prüfen.',
  myUpdates: 'Meine Updates',
  myUpdatesIntro:
    'Fragen, denen Sie folgen. Jede Prüfung starten Sie selbst; Ask vergleicht sie mit Ihrer zuletzt gespeicherten Antwort und zeigt nur, was die Quellen belegen.',
  empty: 'Sie folgen noch keiner Frage. Nutzen Sie „Dieser Frage folgen“ bei einer Antwort.',
  signedOut: 'Melden Sie sich an, um Ihre gefolgten Fragen zu sehen.',
  unavailable: 'Gefolgte Fragen sind derzeit nicht verfügbar.',
  network: 'Ask ist nicht erreichbar. Ihre gefolgten Fragen sind unverändert.',
  baseline: (asOf, age) => `Zuletzt gespeicherte Antwort: ${asOf} (${age})`,
  noBaseline: 'Noch keine gespeicherte Antwort',
  lastChecked: (when) => `Letzte Prüfung: ${when}`,
  lastSuccessful: (when) => `Letzte abgeschlossene Prüfung: ${when}`,
  neverChecked: 'Seit dem Folgen nicht geprüft',
  checkForChanges: 'Auf Änderungen prüfen',
  checkCost: 'Eine Prüfung führt eine neue Suche und Antwort aus und zählt zu Ihrer täglichen Nutzung.',
  checkTooSoon: (m) => `Gerade geprüft. Eine neue Prüfung ist in etwa ${m} Min. möglich.`,
  paused: 'Pausiert',
  pause: 'Pausieren',
  resume: 'Fortsetzen',
  edit: 'Bearbeiten',
  save: 'Speichern',
  cancel: 'Abbrechen',
  titleLabel: 'Name',
  questionLabel: 'Frage',
  editNote: 'Eine geänderte Frage startet einen neuen Vergleich: Die nächste Prüfung wird der neue Ausgangspunkt.',
  remove: 'Nicht mehr folgen',
  removeConfirm: 'Dieser Frage nicht mehr folgen? Gespeicherte Antworten und Prüfverlauf werden gelöscht.',
  removed: 'Sie folgen dieser Frage nicht mehr.',
  history: 'Gespeicherte Antworten',
  outcome: {
    INCOMPLETE_CHECK: 'Prüfung unvollständig',
    INSUFFICIENT_BASELINE: 'Neuer Ausgangspunkt gespeichert',
    CORRECTION: 'Korrektur gemeldet',
    MATERIAL_CHANGE: 'Änderung gemeldet',
    NEW_EVIDENCE: 'Neue Berichte',
    UNCHANGED: 'Keine neuen Berichte',
    NO_RELEVANT_UPDATE: 'Kein relevantes Update gefunden',
  },
  outcomeDetail: {
    INCOMPLETE_CHECK:
      'Die Suche konnte nicht abgeschlossen werden – das heißt also nicht „nichts hat sich geändert“. Ihre zuletzt gespeicherte Antwort bleibt unverändert.',
    INSUFFICIENT_BASELINE:
      'Es gab keine belegte Antwort zum Vergleich (oder die Frage wurde geändert), daher ist diese Prüfung der neue Ausgangspunkt.',
    CORRECTION:
      'Eine Quelle hat einen ihrer verwalteten Datensätze überarbeitet, oder ein neu veröffentlichter Bericht gibt an, frühere Berichte zu korrigieren. Öffnen Sie ihn, um zu sehen, was sich geändert hat.',
    MATERIAL_CHANGE: 'Seit Ihrer zuletzt gespeicherten Antwort veröffentlichte Berichte belegen die folgenden Punkte.',
    NEW_EVIDENCE: 'Seit Ihrer zuletzt gespeicherten Antwort wurden neue Berichte veröffentlicht. Sie sind unten aufgeführt.',
    UNCHANGED:
      'Die gefundenen Quellen sind dieselben, die Ihre zuletzt gespeicherte Antwort bereits nutzte. Neue Formulierungen allein gelten nicht als Änderung.',
    NO_RELEVANT_UPDATE:
      'Die Suche wurde abgeschlossen, fand aber keine relevanten neuen Berichte. Das heißt nicht, dass nichts geschieht.',
  },
  structuredNew: 'Neue verwaltete Datensätze',
  structuredLate: 'Jetzt hinzugefügte Datensätze zu früheren Daten',
  structuredLateNote: 'Nach Ihrer zuletzt gespeicherten Antwort aufgenommen, aber davor datiert. Nicht als neues Ereignis gezählt.',
  structuredRevised: 'Von der Quelle überarbeitete Datensätze',
  structuredUnassessed: (classes) => `Strukturierte Daten in dieser Prüfung nicht bewertet: ${classes}.`,
  structuredNotSeen: (n) => `Frühere Datensätze diesmal nicht geliefert: ${n}. Das ist kein Widerruf.`,
  structuredCarried: (n) => `Unveränderte Datensätze seit Ihrer zuletzt gespeicherten Antwort: ${n}.`,
  partial: (sources) => `Einige Quellen konnten nicht geprüft werden: ${sources}.`,
  newEvidence: 'Neue Berichte',
  supportedChanges: 'Was die neuen Berichte belegen',
  possibleCorrections: 'Gemeldete Korrekturen',
  correctionNote: 'Anhand der Überschrift markiert; Ask entscheidet nicht, was eine Korrektur aufhebt.',
  earlierFound: 'Frühere Berichte, jetzt gefunden',
  earlierFoundNote: 'Vor Ihrer zuletzt gespeicherten Antwort veröffentlicht. Der Vollständigkeit halber gezeigt, nicht als Änderung gezählt.',
  notSeen: (n) => `${n} frühere Quelle(n) wurde(n) von dieser Suche nicht erneut geliefert. Das ist kein Widerruf.`,
  carriedOver: (n) => `Aus Ihrer zuletzt gespeicherten Antwort übernommene Quellen: ${n}.`,
  expiredNotNote: 'Das Ablaufen amtlicher Mitteilungen wird nicht bewertet.',
  checkBanner: (title, asOf) => `„${title}“ wird auf Änderungen seit ${asOf} geprüft.`,
  checkBannerHint: 'Die Frage steht unten bereit. Nichts läuft, bevor Sie sie senden.',
  checkRecording: 'Vergleich mit Ihrer zuletzt gespeicherten Antwort…',
  checkRecorded: 'Prüfung in „Meine Updates“ gespeichert.',
  checkNotRecorded: 'Diese Antwort wurde nicht als Prüfung gespeichert. Ihre gefolgte Frage ist unverändert.',
  checkPausedBanner: 'Diese gefolgte Frage ist pausiert. Setzen Sie sie in „Meine Updates“ fort, um sie zu prüfen.',
  openMyUpdates: '„Meine Updates“ öffnen',
  ageDays: (n) => `vor ${n} Tag${n === 1 ? '' : 'en'}`,
  ageHours: (n) => `vor ${n} Std.`,
  ageJustNow: 'gerade eben',
  deleteConversation: 'Löschen',
  deleteConversationConfirm: (title) => `„${title}“ löschen? Die Unterhaltung und ihre Antworten werden entfernt.`,
  deleteConversationNote: 'Gefolgte Fragen bleiben erhalten; entfernen Sie sie in „Meine Updates“.',
  deleteConversationBusy: 'Wird gelöscht…',
  deleteConversationFailed: 'Nicht gelöscht. Bitte erneut versuchen.',
  conversationDeleted: 'Unterhaltung gelöscht.',
  searchingAll: 'Alle Ihre Unterhaltungen werden durchsucht…',
  nameLabel: 'Name, den Ask für Sie verwendet',
  nameHint: 'Optional. Ask übernimmt nie einen Namen aus Ihrer E-Mail-Adresse. Leer lassen für keinen Namen.',
  nameSave: 'Namen speichern',
  nameSaved: 'Name gespeichert.',
  nameCleared: 'Name entfernt.',
  nameInvalid: 'Verwenden Sie Buchstaben, Leerzeichen, Apostrophe, Bindestriche oder Punkte – keine E-Mail-Adresse und keinen Link.',
  nameTooLong: 'Höchstens 40 Zeichen.',
  nameFailed: 'Nicht gespeichert. Ihr Name ist unverändert.',
  greeting: (name) => `Willkommen zurück, ${name}.`,
};

export const ES: FollowStrings = {
  follow: 'Seguir esta pregunta',
  following: 'Siguiendo',
  followFailed: 'No se siguió. No se cambió nada.',
  followNote: 'Guardada en Mis actualizaciones con esta respuesta como punto de partida. Nada se ejecuta hasta que compruebes.',
  myUpdates: 'Mis actualizaciones',
  myUpdatesIntro:
    'Las preguntas que sigues. Cada comprobación la inicias tú; Ask la compara con tu última respuesta guardada y solo muestra lo que respaldan las fuentes.',
  empty: 'Aún no sigues ninguna pregunta. Usa «Seguir esta pregunta» en una respuesta.',
  signedOut: 'Inicia sesión para ver las preguntas que sigues.',
  unavailable: 'Las preguntas seguidas no están disponibles ahora.',
  network: 'No se pudo conectar con Ask. Tus preguntas seguidas no han cambiado.',
  baseline: (asOf, age) => `Última respuesta guardada: ${asOf} (${age})`,
  noBaseline: 'Aún no hay respuesta guardada',
  lastChecked: (when) => `Última comprobación: ${when}`,
  lastSuccessful: (when) => `Última comprobación completada: ${when}`,
  neverChecked: 'Sin comprobar desde que la sigues',
  checkForChanges: 'Comprobar cambios',
  checkCost: 'Una comprobación ejecuta una nueva búsqueda y respuesta, y cuenta para tu uso diario.',
  checkTooSoon: (m) => `Comprobada hace un momento. Podrás volver a comprobar en unos ${m} min.`,
  paused: 'En pausa',
  pause: 'Pausar',
  resume: 'Reanudar',
  edit: 'Editar',
  save: 'Guardar',
  cancel: 'Cancelar',
  titleLabel: 'Nombre',
  questionLabel: 'Pregunta',
  editNote: 'Cambiar la pregunta inicia una nueva comparación: la próxima comprobación será el nuevo punto de partida.',
  remove: 'Dejar de seguir',
  removeConfirm: '¿Dejar de seguir esta pregunta? Se eliminarán sus respuestas guardadas y su historial de comprobaciones.',
  removed: 'Ya no la sigues.',
  history: 'Respuestas guardadas',
  outcome: {
    INCOMPLETE_CHECK: 'Comprobación incompleta',
    INSUFFICIENT_BASELINE: 'Nuevo punto de partida guardado',
    CORRECTION: 'Corrección publicada',
    MATERIAL_CHANGE: 'Cambio publicado',
    NEW_EVIDENCE: 'Nuevas informaciones',
    UNCHANGED: 'Sin nuevas informaciones',
    NO_RELEVANT_UPDATE: 'No se encontró ninguna actualización relevante',
  },
  outcomeDetail: {
    INCOMPLETE_CHECK:
      'La búsqueda no pudo completarse, así que esto no es un «nada ha cambiado». Tu última respuesta guardada se mantiene igual.',
    INSUFFICIENT_BASELINE:
      'No había una respuesta con fuentes para comparar (o se editó la pregunta), así que esta comprobación es el nuevo punto de partida.',
    CORRECTION:
      'Una fuente revisó uno de sus registros gobernados, o una información publicada recientemente dice que corrige informaciones anteriores. Ábrela para ver qué cambió.',
    MATERIAL_CHANGE: 'Las informaciones publicadas desde tu última respuesta guardada respaldan los puntos siguientes.',
    NEW_EVIDENCE: 'Se publicaron nuevas informaciones desde tu última respuesta guardada. Aparecen a continuación.',
    UNCHANGED:
      'Las fuentes encontradas son las mismas que ya usó tu última respuesta guardada. Una redacción nueva por sí sola no se considera un cambio.',
    NO_RELEVANT_UPDATE:
      'La búsqueda terminó sin encontrar informaciones nuevas relevantes. Eso no significa que no esté pasando nada.',
  },
  structuredNew: 'Nuevos registros gobernados',
  structuredLate: 'Registros añadidos ahora sobre fechas anteriores',
  structuredLateNote: 'Admitidos después de tu última respuesta guardada pero con fecha anterior. No cuentan como un evento nuevo.',
  structuredRevised: 'Registros revisados por su fuente',
  structuredUnassessed: (classes) => `Datos estructurados no evaluados en esta comprobación: ${classes}.`,
  structuredNotSeen: (n) => `Registros anteriores no devueltos esta vez: ${n}. Eso no es una retractación.`,
  structuredCarried: (n) => `Registros sin cambios desde tu última respuesta guardada: ${n}.`,
  partial: (sources) => `No se pudieron comprobar algunas fuentes: ${sources}.`,
  newEvidence: 'Nuevas informaciones',
  supportedChanges: 'Lo que respaldan las nuevas informaciones',
  possibleCorrections: 'Correcciones publicadas',
  correctionNote: 'Señalada por el titular; Ask no decide qué anula una corrección.',
  earlierFound: 'Informaciones anteriores encontradas ahora',
  earlierFoundNote: 'Publicadas antes de tu última respuesta guardada. Se muestran por completitud, no cuentan como cambio.',
  notSeen: (n) => `${n} fuente(s) anterior(es) no aparecieron en esta búsqueda. Eso no es una retractación.`,
  carriedOver: (n) => `Fuentes conservadas de tu última respuesta guardada: ${n}.`,
  expiredNotNote: 'No se evalúa la caducidad de los avisos oficiales.',
  checkBanner: (title, asOf) => `Comprobando cambios en «${title}» desde el ${asOf}.`,
  checkBannerHint: 'La pregunta está lista abajo. Nada se ejecuta hasta que la envíes.',
  checkRecording: 'Comparando con tu última respuesta guardada…',
  checkRecorded: 'Comprobación guardada en Mis actualizaciones.',
  checkNotRecorded: 'Esta respuesta no se guardó como comprobación. Tu pregunta seguida no ha cambiado.',
  checkPausedBanner: 'Esta pregunta seguida está en pausa. Reanúdala en Mis actualizaciones para comprobarla.',
  openMyUpdates: 'Abrir Mis actualizaciones',
  ageDays: (n) => `hace ${n} día${n === 1 ? '' : 's'}`,
  ageHours: (n) => `hace ${n} h`,
  ageJustNow: 'ahora mismo',
  deleteConversation: 'Eliminar',
  deleteConversationConfirm: (title) => `¿Eliminar «${title}»? Se eliminarán la conversación y sus respuestas.`,
  deleteConversationNote: 'Las preguntas seguidas se conservan; quítalas en Mis actualizaciones.',
  deleteConversationBusy: 'Eliminando…',
  deleteConversationFailed: 'No se eliminó. Inténtalo de nuevo.',
  conversationDeleted: 'Conversación eliminada.',
  searchingAll: 'Buscando en todas tus conversaciones…',
  nameLabel: 'Nombre que Ask usa contigo',
  nameHint: 'Opcional. Ask nunca toma un nombre de tu correo electrónico. Déjalo vacío para no usar nombre.',
  nameSave: 'Guardar nombre',
  nameSaved: 'Nombre guardado.',
  nameCleared: 'Nombre eliminado.',
  nameInvalid: 'Usa letras, espacios, apóstrofos, guiones o puntos; no un correo electrónico ni un enlace.',
  nameTooLong: 'Usa 40 caracteres como máximo.',
  nameFailed: 'No se guardó. Tu nombre no ha cambiado.',
  greeting: (name) => `Hola de nuevo, ${name}.`,
};

export const PT: FollowStrings = {
  follow: 'Seguir esta pergunta',
  following: 'A seguir',
  followFailed: 'Não foi seguida. Nada foi alterado.',
  followNote: 'Guardada em As minhas atualizações com esta resposta como ponto de partida. Nada é executado até verificar.',
  myUpdates: 'As minhas atualizações',
  myUpdatesIntro:
    'As perguntas que segue. Cada verificação é iniciada por si; o Ask compara-a com a sua última resposta guardada e mostra apenas o que as fontes confirmam.',
  empty: 'Ainda não segue nenhuma pergunta. Use «Seguir esta pergunta» numa resposta.',
  signedOut: 'Inicie sessão para ver as perguntas que segue.',
  unavailable: 'As perguntas seguidas não estão disponíveis neste momento.',
  network: 'Não foi possível contactar o Ask. As suas perguntas seguidas não foram alteradas.',
  baseline: (asOf, age) => `Última resposta guardada: ${asOf} (${age})`,
  noBaseline: 'Ainda sem resposta guardada',
  lastChecked: (when) => `Última verificação: ${when}`,
  lastSuccessful: (when) => `Última verificação concluída: ${when}`,
  neverChecked: 'Não verificada desde que a segue',
  checkForChanges: 'Verificar alterações',
  checkCost: 'Uma verificação executa uma nova pesquisa e resposta, e conta para a sua utilização diária.',
  checkTooSoon: (m) => `Verificada há instantes. Pode verificar novamente dentro de cerca de ${m} min.`,
  paused: 'Em pausa',
  pause: 'Pausar',
  resume: 'Retomar',
  edit: 'Editar',
  save: 'Guardar',
  cancel: 'Cancelar',
  titleLabel: 'Nome',
  questionLabel: 'Pergunta',
  editNote: 'Alterar a pergunta inicia uma nova comparação: a próxima verificação passa a ser o novo ponto de partida.',
  remove: 'Deixar de seguir',
  removeConfirm: 'Deixar de seguir esta pergunta? As respostas guardadas e o histórico de verificações serão eliminados.',
  removed: 'Já não segue esta pergunta.',
  history: 'Respostas guardadas',
  outcome: {
    INCOMPLETE_CHECK: 'Verificação incompleta',
    INSUFFICIENT_BASELINE: 'Novo ponto de partida guardado',
    CORRECTION: 'Correção noticiada',
    MATERIAL_CHANGE: 'Alteração noticiada',
    NEW_EVIDENCE: 'Novas notícias',
    UNCHANGED: 'Sem novas notícias',
    NO_RELEVANT_UPDATE: 'Nenhuma atualização relevante encontrada',
  },
  outcomeDetail: {
    INCOMPLETE_CHECK:
      'A pesquisa não pôde ser concluída, por isso isto não é um «nada mudou». A sua última resposta guardada mantém-se.',
    INSUFFICIENT_BASELINE:
      'Não havia uma resposta com fontes para comparar (ou a pergunta foi editada), por isso esta verificação é o novo ponto de partida.',
    CORRECTION:
      'Uma fonte reviu um dos seus registos governados, ou uma notícia publicada recentemente diz que corrige notícias anteriores. Abra-a para ver o que mudou.',
    MATERIAL_CHANGE: 'Notícias publicadas desde a sua última resposta guardada confirmam os pontos abaixo.',
    NEW_EVIDENCE: 'Foram publicadas novas notícias desde a sua última resposta guardada. Estão listadas abaixo.',
    UNCHANGED:
      'As fontes encontradas são as que a sua última resposta guardada já usava. Uma nova redação, por si só, não é considerada uma alteração.',
    NO_RELEVANT_UPDATE:
      'A pesquisa terminou sem encontrar notícias novas relevantes. Isso não significa que nada esteja a acontecer.',
  },
  structuredNew: 'Novos registos governados',
  structuredLate: 'Registos adicionados agora sobre datas anteriores',
  structuredLateNote: 'Admitidos depois da sua última resposta guardada, mas datados antes. Não contam como novo acontecimento.',
  structuredRevised: 'Registos revistos pela fonte',
  structuredUnassessed: (classes) => `Dados estruturados não avaliados nesta verificação: ${classes}.`,
  structuredNotSeen: (n) => `Registos anteriores não devolvidos desta vez: ${n}. Isso não é uma retratação.`,
  structuredCarried: (n) => `Registos inalterados desde a sua última resposta guardada: ${n}.`,
  partial: (sources) => `Não foi possível verificar algumas fontes: ${sources}.`,
  newEvidence: 'Novas notícias',
  supportedChanges: 'O que as novas notícias confirmam',
  possibleCorrections: 'Correções noticiadas',
  correctionNote: 'Assinalada pelo título; o Ask não decide o que uma correção anula.',
  earlierFound: 'Notícias anteriores encontradas agora',
  earlierFoundNote: 'Publicadas antes da sua última resposta guardada. Mostradas por completude, não contam como alteração.',
  notSeen: (n) => `${n} fonte(s) anterior(es) não foram devolvidas por esta pesquisa. Isso não é uma retratação.`,
  carriedOver: (n) => `Fontes mantidas da sua última resposta guardada: ${n}.`,
  expiredNotNote: 'A caducidade de avisos oficiais não é avaliada.',
  checkBanner: (title, asOf) => `A verificar alterações em «${title}» desde ${asOf}.`,
  checkBannerHint: 'A pergunta está pronta abaixo. Nada é executado até a enviar.',
  checkRecording: 'A comparar com a sua última resposta guardada…',
  checkRecorded: 'Verificação guardada em As minhas atualizações.',
  checkNotRecorded: 'Esta resposta não foi guardada como verificação. A sua pergunta seguida não foi alterada.',
  checkPausedBanner: 'Esta pergunta seguida está em pausa. Retome-a em As minhas atualizações para a verificar.',
  openMyUpdates: 'Abrir As minhas atualizações',
  ageDays: (n) => `há ${n} dia${n === 1 ? '' : 's'}`,
  ageHours: (n) => `há ${n} h`,
  ageJustNow: 'agora mesmo',
  deleteConversation: 'Eliminar',
  deleteConversationConfirm: (title) => `Eliminar «${title}»? A conversa e as respostas serão removidas.`,
  deleteConversationNote: 'As perguntas seguidas mantêm-se; remova-as em As minhas atualizações.',
  deleteConversationBusy: 'A eliminar…',
  deleteConversationFailed: 'Não foi eliminada. Tente novamente.',
  conversationDeleted: 'Conversa eliminada.',
  searchingAll: 'A pesquisar em todas as suas conversas…',
  nameLabel: 'Nome que o Ask usa para si',
  nameHint: 'Opcional. O Ask nunca obtém um nome a partir do seu e-mail. Deixe vazio para não usar nome.',
  nameSave: 'Guardar nome',
  nameSaved: 'Nome guardado.',
  nameCleared: 'Nome removido.',
  nameInvalid: 'Use letras, espaços, apóstrofos, hífenes ou pontos — não um endereço de e-mail nem uma ligação.',
  nameTooLong: 'Use no máximo 40 caracteres.',
  nameFailed: 'Não foi guardado. O seu nome não foi alterado.',
  greeting: (name) => `Bem-vindo de volta, ${name}.`,
};

export const AR: FollowStrings = {
  follow: 'متابعة هذا السؤال',
  following: 'تتابعه',
  followFailed: 'لم تتم المتابعة. لم يتغير شيء.',
  followNote: 'حُفظ في «تحديثاتي» مع هذه الإجابة كنقطة بداية. لا يُشغَّل شيء حتى تتحقق بنفسك.',
  myUpdates: 'تحديثاتي',
  myUpdatesIntro:
    'الأسئلة التي تتابعها. كل تحقق تبدؤه بنفسك؛ يقارنه Ask بآخر إجابة محفوظة ولا يعرض إلا ما تدعمه المصادر.',
  empty: 'لا تتابع أي سؤال بعد. استخدم «متابعة هذا السؤال» في إحدى الإجابات.',
  signedOut: 'سجّل الدخول لرؤية الأسئلة التي تتابعها.',
  unavailable: 'الأسئلة المتابَعة غير متاحة حاليًا.',
  network: 'تعذّر الوصول إلى Ask. أسئلتك المتابَعة لم تتغير.',
  baseline: (asOf, age) => `آخر إجابة محفوظة: ${asOf} (${age})`,
  noBaseline: 'لا توجد إجابة محفوظة بعد',
  lastChecked: (when) => `آخر تحقق: ${when}`,
  lastSuccessful: (when) => `آخر تحقق مكتمل: ${when}`,
  neverChecked: 'لم يُتحقق منه منذ بدء المتابعة',
  checkForChanges: 'التحقق من التغييرات',
  checkCost: 'يُجري التحقق بحثًا جديدًا وإجابة جديدة، ويُحتسب ضمن استخدامك اليومي.',
  checkTooSoon: (m) => `تم التحقق للتو. يمكنك التحقق مجددًا بعد نحو ${m} دقيقة.`,
  paused: 'متوقف مؤقتًا',
  pause: 'إيقاف مؤقت',
  resume: 'استئناف',
  edit: 'تعديل',
  save: 'حفظ',
  cancel: 'إلغاء',
  titleLabel: 'الاسم',
  questionLabel: 'السؤال',
  editNote: 'تغيير السؤال يبدأ مقارنة جديدة: يصبح التحقق التالي نقطة البداية الجديدة.',
  remove: 'إيقاف المتابعة',
  removeConfirm: 'إيقاف متابعة هذا السؤال؟ ستُحذف إجاباته المحفوظة وسجل التحقق.',
  removed: 'لم تعد تتابع هذا السؤال.',
  history: 'الإجابات المحفوظة',
  outcome: {
    INCOMPLETE_CHECK: 'تحقق غير مكتمل',
    INSUFFICIENT_BASELINE: 'حُفظت نقطة بداية جديدة',
    CORRECTION: 'أُبلغ عن تصحيح',
    MATERIAL_CHANGE: 'أُبلغ عن تغيير',
    NEW_EVIDENCE: 'تقارير جديدة',
    UNCHANGED: 'لا تقارير جديدة',
    NO_RELEVANT_UPDATE: 'لم يُعثر على تحديث ذي صلة',
  },
  outcomeDetail: {
    INCOMPLETE_CHECK:
      'تعذّر إكمال البحث، لذا فهذا ليس «لا شيء تغيّر». تبقى آخر إجابة محفوظة كما هي.',
    INSUFFICIENT_BASELINE:
      'لم تكن هناك إجابة مستندة إلى مصادر للمقارنة (أو عُدّل السؤال)، لذا يصبح هذا التحقق نقطة البداية الجديدة.',
    CORRECTION:
      'راجع مصدرٌ أحد سجلاته الموثّقة، أو يذكر تقرير نُشر حديثًا أنه يصحح تقارير سابقة. افتحه لترى ما الذي تغيّر.',
    MATERIAL_CHANGE: 'تقارير نُشرت منذ آخر إجابة محفوظة تدعم النقاط أدناه.',
    NEW_EVIDENCE: 'نُشرت تقارير جديدة منذ آخر إجابة محفوظة. وهي مدرجة أدناه.',
    UNCHANGED:
      'المصادر التي عُثر عليها هي نفسها التي استخدمتها آخر إجابة محفوظة. الصياغة الجديدة وحدها لا تُعدّ تغييرًا.',
    NO_RELEVANT_UPDATE:
      'اكتمل البحث ولم يعثر على تقارير جديدة ذات صلة. هذا لا يعني أن لا شيء يحدث.',
  },
  structuredNew: 'سجلات موثّقة جديدة',
  structuredLate: 'سجلات أُضيفت الآن عن تواريخ سابقة',
  structuredLateNote: 'قُبلت بعد آخر إجابة محفوظة لكنها مؤرخة قبلها. لا تُحتسب حدثًا جديدًا.',
  structuredRevised: 'سجلات راجعها مصدرها',
  structuredUnassessed: (classes) => `بيانات منظَّمة لم تُقيَّم في هذا التحقق: ${classes}.`,
  structuredNotSeen: (n) => `سجلات سابقة لم تُرجَع هذه المرة: ${n}. هذا ليس سحبًا.`,
  structuredCarried: (n) => `سجلات لم تتغير منذ آخر إجابة محفوظة: ${n}.`,
  partial: (sources) => `تعذّر التحقق من بعض المصادر: ${sources}.`,
  newEvidence: 'تقارير جديدة',
  supportedChanges: 'ما تدعمه التقارير الجديدة',
  possibleCorrections: 'تصحيحات مُبلغ عنها',
  correctionNote: 'مُعلَّمة بحسب العنوان؛ لا يقرر Ask ما الذي يلغيه التصحيح.',
  earlierFound: 'تقارير سابقة عُثر عليها الآن',
  earlierFoundNote: 'نُشرت قبل آخر إجابة محفوظة. تُعرض للاكتمال ولا تُحتسب تغييرًا.',
  notSeen: (n) => `لم يُرجع هذا البحث ${n} من المصادر السابقة. هذا ليس سحبًا للخبر.`,
  carriedOver: (n) => `مصادر مستمرة من آخر إجابة محفوظة: ${n}.`,
  expiredNotNote: 'لا يُقيَّم انتهاء صلاحية الإشعارات الرسمية.',
  checkBanner: (title, asOf) => `جارٍ التحقق من التغييرات في «${title}» منذ ${asOf}.`,
  checkBannerHint: 'السؤال جاهز أدناه. لا يُشغَّل شيء حتى ترسله.',
  checkRecording: 'جارٍ المقارنة بآخر إجابة محفوظة…',
  checkRecorded: 'حُفظ التحقق في «تحديثاتي».',
  checkNotRecorded: 'لم تُحفظ هذه الإجابة كتحقق. سؤالك المتابَع لم يتغير.',
  checkPausedBanner: 'هذا السؤال المتابَع متوقف مؤقتًا. استأنفه في «تحديثاتي» للتحقق منه.',
  openMyUpdates: 'فتح «تحديثاتي»',
  ageDays: (n) => `منذ ${n} يوم`,
  ageHours: (n) => `منذ ${n} ساعة`,
  ageJustNow: 'الآن',
  deleteConversation: 'حذف',
  deleteConversationConfirm: (title) => `حذف «${title}»؟ ستُحذف المحادثة وإجاباتها.`,
  deleteConversationNote: 'تبقى الأسئلة المتابَعة؛ أزلها من «تحديثاتي».',
  deleteConversationBusy: 'جارٍ الحذف…',
  deleteConversationFailed: 'لم يُحذف. حاول مرة أخرى.',
  conversationDeleted: 'حُذفت المحادثة.',
  searchingAll: 'جارٍ البحث في جميع محادثاتك…',
  nameLabel: 'الاسم الذي يستخدمه Ask لك',
  nameHint: 'اختياري. لا يأخذ Ask اسمًا من بريدك الإلكتروني أبدًا. اتركه فارغًا لعدم استخدام اسم.',
  nameSave: 'حفظ الاسم',
  nameSaved: 'حُفظ الاسم.',
  nameCleared: 'أُزيل الاسم.',
  nameInvalid: 'استخدم الحروف أو المسافات أو الفواصل العليا أو الشرطات أو النقاط — لا عنوان بريد إلكتروني ولا رابطًا.',
  nameTooLong: 'استخدم 40 حرفًا كحد أقصى.',
  nameFailed: 'لم يُحفظ. اسمك لم يتغير.',
  greeting: (name) => `مرحبًا بعودتك، ${name}.`,
};
