import type {
  AgreementPoint,
  ClaimReference,
  DifferenceItem,
  DirectionalEligibility,
  EvidenceSufficiency,
  RelationalComposition,
  SourcedClaim,
  TimelineEvent,
} from '@globalnews-ai/shared';

/**
 * Milestone #41 — Trusted Relational Composition.
 *
 * Operates EXCLUSIVELY on already-FINAL VALIDATED result structures —
 * never on candidate/provider output, never on request-local S/R-label
 * references. There is no model-facing schema for anything in this
 * file: every ClaimReference is generated by this function itself
 * while iterating the final validated arrays, so there is no untrusted
 * index or ID for a malformed/dropped candidate entry to shift onto,
 * and no duplicate-reference ambiguity to resolve — both attack classes
 * are structurally inapplicable here, not merely mitigated.
 *
 * `summary` is selected from a small, fixed set of backend-authored
 * templates (see buildSummary below) — there is no free-form model
 * prose anywhere in the returned RelationalComposition. This is the
 * direct fix for the trust gap identified during M41 design review:
 * attaching a boolean/label to unsafe model prose does not make that
 * prose safe, so no such prose is ever admitted into this structure at
 * all.
 */

interface RelationalSupportBearing {
  relationalSupport?: {
    direction: string;
    assessments: Array<{ articleId: string }>;
  };
}

function collectReferences<T extends RelationalSupportBearing>(
  section: ClaimReference['section'],
  entries: T[],
): {
  supportingClaims: ClaimReference[];
  reverseClaims: ClaimReference[];
  associationOnlyClaims: ClaimReference[];
  mixedClaims: ClaimReference[];
  unclearOrNonSubstantiveClaims: ClaimReference[];
  supportingArticleIds: string[];
} {
  const supportingClaims: ClaimReference[] = [];
  const reverseClaims: ClaimReference[] = [];
  const associationOnlyClaims: ClaimReference[] = [];
  const mixedClaims: ClaimReference[] = [];
  const unclearOrNonSubstantiveClaims: ClaimReference[] = [];
  const supportingArticleIds: string[] = [];

  entries.forEach((entry, index) => {
    const support = entry.relationalSupport;
    if (!support) return;

    const ref: ClaimReference = { section, index };

    switch (support.direction) {
      case 'requested-direction':
      case 'bidirectional':
        supportingClaims.push(ref);
        // Only claims whose OWN aggregate direction is
        // requested-direction/bidirectional ever contribute an
        // articleId here. A 'mixed' claim's assessments are never
        // reached into, even if one of them is individually
        // requested-direction — M40's own aggregation already
        // collapsed that disagreement into 'mixed', and this function
        // does not reverse that collapse.
        for (const assessment of support.assessments) {
          supportingArticleIds.push(assessment.articleId);
        }
        break;
      case 'reverse-direction':
        reverseClaims.push(ref);
        break;
      case 'association-only':
        associationOnlyClaims.push(ref);
        break;
      case 'mixed':
        mixedClaims.push(ref);
        break;
      case 'unclear':
      case 'non-substantive':
        unclearOrNonSubstantiveClaims.push(ref);
        break;
      default:
        break;
    }
  });

  return {
    supportingClaims,
    reverseClaims,
    associationOnlyClaims,
    mixedClaims,
    unclearOrNonSubstantiveClaims,
    supportingArticleIds,
  };
}

function deriveEvidenceSufficiency(
  distinctSupportingArticleCount: number,
  hasReverseClaims: boolean,
  hasMixedClaims: boolean,
): EvidenceSufficiency {
  if (distinctSupportingArticleCount === 0) return 'insufficient';
  if (hasReverseClaims || hasMixedClaims) return 'limited';
  return distinctSupportingArticleCount >= 2 ? 'adequate' : 'limited';
}

/**
 * Milestone #41 — fixed backend template selection. `x`/`y` are the
 * same authoritative relationalContext values M40 already threads
 * through (see resolve-relational-evidence-assessment.util.ts) — never
 * re-derived here. No branch below asserts causality or a stronger
 * conclusion than the evidence classification actually supports.
 */
function buildSummary(
  x: string,
  y: string,
  directionalEligibility: DirectionalEligibility,
  hasReverseClaims: boolean,
  hasAssociationOnlyClaims: boolean,
  hasMixedClaims: boolean,
  evidenceSufficiency: EvidenceSufficiency,
): string {
  const contradictionPresent = hasReverseClaims || hasMixedClaims;

  if (directionalEligibility === 'supported') {
    if (contradictionPresent) {
      return `Available reporting contains evidence supporting the requested relationship from "${x}" to "${y}"; other reporting presents a reverse or mixed picture.`;
    }
    if (evidenceSufficiency === 'adequate') {
      return `Available reporting contains evidence, from multiple distinct articles, supporting the requested relationship from "${x}" to "${y}".`;
    }
    return `Available reporting contains evidence supporting the requested relationship from "${x}" to "${y}", based on limited sourcing.`;
  }

  if (hasReverseClaims) {
    return `Available reporting contains evidence for the reverse relationship, from "${y}" to "${x}", rather than the direction asked about.`;
  }
  if (hasAssociationOnlyClaims) {
    return `Available reporting links "${x}" and "${y}", but the validated evidence does not establish the requested direction.`;
  }
  if (hasMixedClaims) {
    return `Available reporting contains conflicting relationship evidence that does not establish the requested direction.`;
  }
  return `Available reporting does not provide enough validated evidence to establish the requested relationship.`;
}

/**
 * Builds the Milestone #41 RelationalComposition from FINAL VALIDATED
 * result structures. Returns undefined when relationalContextPresent
 * was false for this request — the caller (validate-analysis-result.ts)
 * is responsible for that gate; this function assumes it has already
 * been applied and x/y are genuinely authoritative for this request.
 */
export function buildRelationalComposition(
  x: string,
  y: string,
  keyFacts: SourcedClaim[],
  agreements: AgreementPoint[],
  differences: DifferenceItem[],
  timeline: TimelineEvent[],
): RelationalComposition {
  const positions = differences.flatMap((item) => item.positions);

  const keyFactsRefs = collectReferences('keyFacts', keyFacts);
  const agreementsRefs = collectReferences('agreements', agreements);
  const differencesRefs = collectReferences('differences', positions);
  const timelineRefs = collectReferences('timeline', timeline);

  const supportingClaims = [
    ...keyFactsRefs.supportingClaims,
    ...agreementsRefs.supportingClaims,
    ...differencesRefs.supportingClaims,
    ...timelineRefs.supportingClaims,
  ];
  const reverseClaims = [
    ...keyFactsRefs.reverseClaims,
    ...agreementsRefs.reverseClaims,
    ...differencesRefs.reverseClaims,
    ...timelineRefs.reverseClaims,
  ];
  const associationOnlyClaims = [
    ...keyFactsRefs.associationOnlyClaims,
    ...agreementsRefs.associationOnlyClaims,
    ...differencesRefs.associationOnlyClaims,
    ...timelineRefs.associationOnlyClaims,
  ];
  const mixedClaims = [
    ...keyFactsRefs.mixedClaims,
    ...agreementsRefs.mixedClaims,
    ...differencesRefs.mixedClaims,
    ...timelineRefs.mixedClaims,
  ];
  const unclearOrNonSubstantiveClaims = [
    ...keyFactsRefs.unclearOrNonSubstantiveClaims,
    ...agreementsRefs.unclearOrNonSubstantiveClaims,
    ...differencesRefs.unclearOrNonSubstantiveClaims,
    ...timelineRefs.unclearOrNonSubstantiveClaims,
  ];

  // Deduplicate by distinct articleId — two claims citing the same
  // article are ONE supporting article, never two. Do NOT count claims.
  const distinctSupportingArticleIds = new Set([
    ...keyFactsRefs.supportingArticleIds,
    ...agreementsRefs.supportingArticleIds,
    ...differencesRefs.supportingArticleIds,
    ...timelineRefs.supportingArticleIds,
  ]);

  const directionalEligibility: DirectionalEligibility =
    supportingClaims.length > 0 ? 'supported' : 'unsupported';

  const evidenceSufficiency = deriveEvidenceSufficiency(
    distinctSupportingArticleIds.size,
    reverseClaims.length > 0,
    mixedClaims.length > 0,
  );

  const summary = buildSummary(
    x,
    y,
    directionalEligibility,
    reverseClaims.length > 0,
    associationOnlyClaims.length > 0,
    mixedClaims.length > 0,
    evidenceSufficiency,
  );

  return {
    directionalEligibility,
    evidenceSufficiency,
    summary,
    supportingClaims,
    reverseClaims,
    associationOnlyClaims,
    mixedClaims,
    unclearOrNonSubstantiveClaims,
  };
}
