import type { Metadata } from 'next';
import type { LanguageCode } from '@globalnews-ai/shared';
import { absoluteUrl, resolveSiteOrigin } from './siteOrigin';
import { classify } from './routes';

/**
 * ═══ ONE METADATA BUILDER, SO THE FOUR FACTS CANNOT DISAGREE ═══════════
 *
 * A page's title, its canonical URL, its robots directive and its social
 * card are four statements about the SAME page. Written separately they
 * drift, and the drift is invisible: a page can say `noindex` while its
 * Open Graph block advertises it as shareable public content, and both
 * halves look right in isolation.
 *
 * So every route asks for its metadata here, the canonical comes from the
 * path, and the robots directive comes from the registry rather than from
 * whoever edited the page last.
 *
 * FAIL CLOSED ON THE ORIGIN. With no configured origin there is no
 * canonical and no `og:url` — the fields are OMITTED, never guessed.
 *
 * NOTHING HERE READS REQUEST OR SESSION STATE (§N.8). The language is
 * passed in by the caller, which already resolves it from the cookie for
 * its own rendering; this adds no second language mechanism and no second
 * reason for a page to become dynamic.
 */

/** Maps the product's language codes onto the locale form OG expects. */
const OG_LOCALE: Readonly<Record<string, string>> = {
  en: 'en_US',
  pl: 'pl_PL',
};

export interface PageMetadataInput {
  /** Canonical path for this route. Never a query string. */
  readonly path: string;
  readonly title: string;
  readonly description: string;
  readonly language: LanguageCode;
  /**
   * Open Graph type. `website` for every surface this foundation covers —
   * `article` would be a claim about first-party publication that this
   * product does not make (see README §F/§G).
   */
  readonly ogType?: 'website';
}

export function buildPageMetadata(input: PageMetadataInput): Metadata {
  const entry = classify(input.path);
  const origin = resolveSiteOrigin();
  const canonical = absoluteUrl(entry.path, origin);
  const indexable = entry.indexability === 'index' && !entry.userDependent;

  const robots: Metadata['robots'] = indexable
    ? { index: true, follow: true }
    : /*
         `follow: false` as well as `index: false` on user-dependent
         surfaces. A crawler that follows links out of one reader's
         question results is walking a graph generated by that reader,
         which is the discovery surface §B rules out — not merely the
         page itself.
      */
      { index: false, follow: false };

  const metadata: Metadata = {
    title: input.title,
    description: input.description,
    robots,
  };

  /*
    CANONICAL ONLY FOR PUBLIC SURFACES, AND ONLY WHEN WE HAVE AN ORIGIN.
    A canonical tag on a `noindex` page is not harmless: it nominates that
    URL as the published home of the content, which is the opposite of what
    a private or transient surface is claiming.
  */
  if (indexable && canonical !== null) {
    metadata.alternates = { canonical };
  }

  const locale = OG_LOCALE[input.language];

  metadata.openGraph = {
    type: input.ogType ?? 'website',
    title: input.title,
    description: input.description,
    siteName: 'GlobalNews AI',
    ...(locale === undefined ? {} : { locale }),
    /* §K — the social URL FOLLOWS the canonical, never diverges from it. */
    ...(indexable && canonical !== null ? { url: canonical } : {}),
  };

  metadata.twitter = {
    /*
      `summary`, not `summary_large_image`. The large card is a promise of
      a valid representative image; §K permits an image "only when valid"
      and this foundation adds none, because none of these surfaces has a
      per-page image the record actually supports.
    */
    card: 'summary',
    title: input.title,
    description: input.description,
  };

  return metadata;
}

/**
 * The root layout's defaults. `metadataBase` is what lets Next resolve any
 * relative metadata URL a page might declare later; omitted entirely when
 * no origin is configured, rather than defaulted to a guess.
 */
export function buildRootMetadataBase(): Pick<Metadata, 'metadataBase'> {
  const origin = resolveSiteOrigin();
  return origin === null ? {} : { metadataBase: new URL(origin) };
}
