/* ASK R2 · EN/PL SEMANTIC-TWIN CORPUS — 50 pairs, 100 questions.
   TEXT IDENTICAL TO THE R1 DELIVERED RUNNER. Not re-typed: these rows were
   extracted from `inputs/run-matrix.r1.mts` and the runner re-verifies that at
   run time (control CT-0), so a drift in either copy fails the run. */
export type Row = readonly [cat: string, id: string, ctx: boolean, en: string, pl: string];
export const CORPUS: readonly Row[] = [
 ['reference', 'R1', false, 'What is inflation?', 'Czym jest inflacja?'],
 ['reference', 'R2', false, 'Who is the president of Rwanda?', 'Kto jest prezydentem Rwandy?'],
 ['current status', 'C1', false, 'What is the situation on the border right now?', 'Jaka jest sytuacja na granicy w tej chwili?'],
 ['current status', 'C2', false, 'What is the latest on the audit?', 'Jakie są najnowsze informacje o audycie?'],
 ['news', 'N1', false, 'What is happening in Kigali?', 'Co dzieje się w Kigali?'],
 ['news', 'N2', false, 'Show me the latest headlines about the election.', 'Pokaż najnowsze nagłówki o wyborach.'],
 ['politics', 'P1', false, 'What did the minister announce about the budget?', 'Co minister ogłosił w sprawie budżetu?'],
 ['politics', 'P2', false, "What is the government's position on the new law?", 'Jakie jest stanowisko rządu wobec nowej ustawy?'],
 ['economy', 'E1', false, 'What is the latest inflation figure?', 'Jaki jest najnowszy wskaźnik inflacji?'],
 ['economy', 'E2', false, 'How is trade between Poland and Germany developing?', 'Jak rozwija się handel między Polską a Niemcami?'],
 ['security', 'S1', false, 'security situation on the border today', 'sytuacja bezpieczeństwa na granicy dzisiaj'],
 ['security', 'S2', false, 'Is there a military threat near the border?', 'Czy istnieje zagrożenie militarne w pobliżu granicy?'],
 ['geography', 'G1', false, 'What is happening in Poland?', 'Co dzieje się w Polsce?'],
 ['geography', 'G2', false, 'What is happening in the Warsaw region?', 'Co dzieje się w regionie warszawskim?'],
 ['dates/numbers', 'D1', false, 'What happened yesterday in Nairobi?', 'Co wydarzyło się wczoraj w Nairobi?'],
 ['dates/numbers', 'D2', false, 'What were the results in 2026?', 'Jakie były wyniki w 2026 roku?'],
 ['negation', 'X1', false, 'What has not been reported about the audit?', 'Czego nie zgłoszono w sprawie audytu?'],
 ['negation', 'X2', false, 'Which districts did not publish results?', 'Które okręgi nie opublikowały wyników?'],
 ['clarification', 'Q1', false, 'Compare them.', 'Porównaj je.'],
 ['clarification', 'Q2', false, 'Tell me about it.', 'Opowiedz mi o tym.'],
 ['follow-up', 'F1', true, 'And Kenya?', 'A Kenia?'],
 ['follow-up', 'F2', true, 'Tell me more about that.', 'Powiedz mi o tym więcej.'],
 ['current-office', 'O1', false, 'Who is the current president of Kenya?', 'Kto jest obecnie prezydentem Kenii?'],
 ['current-office', 'O2', false, 'Who is the prime minister of Poland right now?', 'Kto jest teraz premierem Polski?'],
 ['explicit country', 'K1', false, 'What is happening in Rwanda?', 'Co dzieje się w Rwandzie?'],
 ['explicit country', 'K2', false, 'Compare Poland and Ukraine.', 'Porównaj Polskę i Ukrainę.'],
 ['entertainment', 'T1', false, 'Which films won awards this year?', 'Jakie filmy zdobyły nagrody w tym roku?'],
 ['entertainment', 'T2', false, 'Who won the music award last night?', 'Kto wygrał nagrodę muzyczną wczoraj wieczorem?'],
 ['stated period', 'PD1', false, 'What changed in the last three months?', 'Co zmieniło się w ciągu ostatnich trzech miesięcy?'],
 ['stated period', 'PD2', false, 'Summarize the situation since January.', 'Podsumuj sytuację od stycznia.'],
 ['date', 'DT1', false, 'What happened on 3 May 2026?', 'Co wydarzyło się 3 maja 2026?'],
 ['date', 'DT2', false, 'What is planned for next week?', 'Co jest planowane w przyszłym tygodniu?'],
 ['number', 'NU1', false, 'How many districts reported results?', 'Ile okręgów zgłosiło wyniki?'],
 ['number', 'NU2', false, 'What was the 2.5 percent change about?', 'Czego dotyczyła zmiana o 2,5 procent?'],
 ['negation', 'NG1', false, 'Which countries did not sign the agreement?', 'Które kraje nie podpisały porozumienia?'],
 ['negation', 'NG2', false, 'Has the border not reopened?', 'Czy granica nie została ponownie otwarta?'],
 ['ambiguity', 'AM1', false, 'Georgia', 'Gruzja'],
 ['ambiguity', 'AM2', false, 'What about it?', 'A co z tym?'],
 ['stable reference', 'RF1', false, 'What is GDP?', 'Czym jest PKB?'],
 ['stable reference', 'RF2', false, 'What does inflation mean?', 'Co oznacza inflacja?'],
 ['science', 'SC1', false, 'What is photosynthesis?', 'Czym jest fotosynteza?'],
 ['science', 'SC2', false, 'How does a vaccine work?', 'Jak działa szczepionka?'],
 ['mathematics', 'MA1', false, 'What is the square root of 144?', 'Ile wynosi pierwiastek kwadratowy z 144?'],
 ['mathematics', 'MA2', false, 'What is 15 percent of 240?', 'Ile to jest 15 procent z 240?'],
 ['engineering', 'EG1', false, 'How does a suspension bridge work?', 'Jak działa most wiszący?'],
 ['engineering', 'EG2', false, 'What is reinforced concrete?', 'Czym jest beton zbrojony?'],
 ['computing', 'CP1', false, 'What is quantum computing?', 'Czym są obliczenia kwantowe?'],
 ['computing', 'CP2', false, 'How does public key encryption work?', 'Jak działa szyfrowanie klucza publicznego?'],
 ['map-origin', 'MP1', false, 'What is happening here?', 'Co się tutaj dzieje?'],
 ['map-origin', 'MP2', false, 'Show me security incidents in this country.', 'Pokaż incydenty bezpieczeństwa w tym kraju.'],
];
export const MAP_ORIGIN = new Set(['MP1', 'MP2']);
export const NON_EQUIVALENT: Record<string, string> = {
  AM1: 'EN "Georgia" names two places (country and US state); PL "Gruzja" names only the country. The ambiguity itself differs, so the questions are not equivalent.',
};
