import type { DisplayLocale } from '@globalnews-ai/shared';
import type { SurfaceId } from '@/lib/i18n/surfaceLocale';

/**
 * GENERATED by scripts/i18n/t2-reconcile-catalogues.cjs — DO NOT EDIT BY HAND.
 *
 * The locales each surface renders COMPLETELY (English first), MEASURED by
 * src/qualification/i18n/surfaceCoverage.ts over every catalogue namespace the surface uses.
 * surfaceLocale.spec.ts asserts this table equals the live measurement; re-run the script
 * after any catalogue change.
 */
export const SURFACE_RENDERABLE: Readonly<Record<SurfaceId, readonly DisplayLocale[]>> = {
  home: ['en', 'pl'],
  askStandalone: ['en', 'pl', 'fr', 'de', 'es', 'pt', 'ar'],
  askRecent: ['en', 'pl', 'fr', 'de', 'es', 'pt', 'ar'],
  saved: ['en', 'pl', 'fr', 'de', 'es', 'pt', 'ar'],
  accountSettings: ['en', 'pl', 'fr', 'de', 'es', 'pt', 'ar'],
  search: ['en', 'pl'],
  map: ['en', 'pl'],
  conflict: ['en', 'pl'],
  energy: ['en', 'pl'],
  market: ['en'],
  humanitarian: ['en'],
  economy: ['en'],
  politics: ['en', 'pl'],
  election: ['en', 'pl'],
  security: ['en'],
  delivery: ['en', 'pl'],
  imihigo: ['en', 'pl'],
  myIntelligence: ['en', 'pl'],
  support: ['en', 'pl'],
  history: ['en'],
  privacy: ['en', 'pl'],
  terms: ['en', 'pl'],
  cookies: ['en', 'pl'],
  sourcePolicy: ['en', 'pl'],
  thirdPartyNotices: ['en', 'pl'],
  workspace: ['en', 'pl'],
  admin: ['en', 'pl'],
  failure: ['en', 'pl'],
  default: ['en', 'pl'],
};
