/** R2 conservative retained-text classifier. See docs/security-r2/REPORT.md for limits. */
export const ACT_OF_VIOLENCE_TERMS: readonly string[] = [
  'shooting',
  'shootings',
  'shot dead',
  'gunfire',
  'gunshot',
  'gunshots',
  'opened fire',
  'stabbing',
  'stabbings',
  'stabbed',
  'killed',
  'killings',
  'fatally injured',
  'murder',
  'murders',
  'murdered',
  'homicide',
  'homicides',
  'manslaughter',
  'assaulted',
  'assault',
  'beaten to death',
  'explosion',
  'explosions',
  'blast',
  'detonated',
  'bombing',
  'bombings',
  'grenade',
  'arson',
  'set ablaze',
  'looting',
  'looted',
  'riot',
  'riots',
  'rioting',
  'armed attack',
  'gun attack',
  'ambush',
  'ambushed',
  'kidnapping',
  'kidnapped',
  'abduction',
  'abducted',
  'hijacking',
  'hijacked',
  'hostage',
  'hostages',
  'armed robbery',
  'shoot-out',
  'shootout',
  'clashes',
  'clashed',
  'violent unrest',
  'casualties',
  'wounded',
];

export const PROTECTIVE_POSTURE_TERMS: readonly string[] = [
  'curfew',
  'state of emergency',
  'security lockdown',
  'security cordon',
  'evacuation order',
  'police deployed',
  'troops deployed',
  'security operation',
  'heightened security',
  'security alert',
];

export const VIOLENCE_OR_POSTURE_TERMS: readonly string[] = [
  ...ACT_OF_VIOLENCE_TERMS,
  ...PROTECTIVE_POSTURE_TERMS,
];

export const ORGANISED_ARMED_ACTOR_TERMS: readonly string[] = [
  'militia',
  'militias',
  'militant',
  'militants',
  'insurgent',
  'insurgents',
  'insurgency',
  'rebel',
  'rebels',
  'armed group',
  'armed groups',
  'armed faction',
  'guerrilla',
  'guerrillas',
  'paramilitary',
  'jihadist',
  'jihadists',
  'extremist group',
  'terrorist group',
  'armed forces',
  'army',
  'military',
  'troops',
  'soldiers',
  'air strike',
  'airstrike',
  'airstrikes',
  'artillery',
  'shelling',
  'offensive',
  'insurrection',
  'warlord',
  'combatants',
  'ceasefire',
  'front line',
  'frontline',
];

export const CIVIL_CRIMINAL_FRAME_TERMS: readonly string[] = [
  'police said',
  'police investigation',
  'police are investigating',
  'under investigation',
  'murder investigation',
  'homicide investigation',
  'criminal investigation',
  'arrested',
  'arrest',
  'arrests',
  'detained a suspect',
  'suspect',
  'suspects',
  'charged with',
  'appeared in court',
  'prosecutors',
  'prosecutor',
  'indicted',
  'remanded',
  'sentenced',
  'manslaughter charge',

  'robbery',
  'robberies',
  'burglary',
  'burglaries',
  'mugging',
  'carjacking',
  'brawl',
  'bar fight',
  'domestic dispute',
  'domestic violence',
  'hit-and-run',
  'road rage',
  'gang-related',
  'organised crime',
  'organized crime',
  'drug-related',
  'trafficking ring',
];

export const POLITICAL_ACTIVITY_TERMS: readonly string[] = [
  'protest',
  'protests',
  'protesters',
  'protestors',
  'demonstration',
  'demonstrations',
  'demonstrators',
  'rally',
  'rallies',
  'march',
  'marches',
  'sit-in',
  'picket',
  'boycott',
  'strike action',
  'general strike',
  'opposition rally',
  'petition',
  'civil disobedience',
  'vigil',
];

export const NON_SECURITY_CAUSE_TERMS: readonly string[] = [
  'flood',
  'floods',
  'flooding',
  'earthquake',
  'landslide',
  'mudslide',
  'drought',
  'famine',
  'cyclone',
  'hurricane',
  'typhoon',
  'wildfire',
  'volcanic',
  'tsunami',
  'heatwave',

  'road accident',
  'traffic accident',
  'bus crash',
  'plane crash',
  'derailment',
  'building collapse',
  'industrial accident',
  'mine collapse',
  'capsized',
  'drowned',

  'outbreak',
  'epidemic',
  'pandemic',
  'cholera',
  'ebola',
  'malaria',
  'measles',
  'vaccination',
];

export function matchTerms(haystack: string, terms: readonly string[]): readonly string[] {
  const text = haystack.toLowerCase();
  const found: string[] = [];
  for (const term of terms) {
    const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, 'i').test(text)) {
      found.push(term);
    }
  }
  return found;
}
