/* eslint-disable */
/**
 * CTO R4 SEVEN-LANGUAGE RULING §5 — LOCALIZED COUNTRY NAMES (identity data, generated, committed).
 *
 * One row per localized registry name: [the name as CLDR writes it in that language, the canonical
 * ISO3 of the EXISTING registry entry]. Generated once from the shared country registry and the
 * CLDR region display names shipped with ICU 78.3 (Node v24.18.1); committed so identity
 * never depends on the runtime ICU build. A parenthesised variant ("Myanmar (Birmanie)") yields
 * both forms. A form that names two registry entries in one language is dropped (never guessed).
 * Canonicalization is direct (localized name → existing ID), never via an English translation.
 * Do not edit by hand: governed aliases live in localized-entities.ts.
 */
export type LocalizedLanguage = 'fr' | 'de' | 'es' | 'pt' | 'ar';

export const LOCALIZED_COUNTRY_NAMES: Readonly<
  Record<LocalizedLanguage, ReadonlyArray<readonly [string, string]>>
> = {
  fr: [
    ['Afghanistan', 'AFG'],
    ['Afrique du Sud', 'ZAF'],
    ['Albanie', 'ALB'],
    ['Algérie', 'DZA'],
    ['Allemagne', 'DEU'],
    ['Andorre', 'AND'],
    ['Angola', 'AGO'],
    ['Antarctique', 'ATA'],
    ['Antigua-et-Barbuda', 'ATG'],
    ['Arabie saoudite', 'SAU'],
    ['Argentine', 'ARG'],
    ['Arménie', 'ARM'],
    ['Australie', 'AUS'],
    ['Autriche', 'AUT'],
    ['Azerbaïdjan', 'AZE'],
    ['Bahamas', 'BHS'],
    ['Bahreïn', 'BHR'],
    ['Bangladesh', 'BGD'],
    ['Barbade', 'BRB'],
    ['Belgique', 'BEL'],
    ['Belize', 'BLZ'],
    ['Bénin', 'BEN'],
    ['Bhoutan', 'BTN'],
    ['Biélorussie', 'BLR'],
    ['Birmanie', 'MMR'],
    ['Bolivie', 'BOL'],
    ['Bosnie-Herzégovine', 'BIH'],
    ['Botswana', 'BWA'],
    ['Brésil', 'BRA'],
    ['Brunei', 'BRN'],
    ['Bulgarie', 'BGR'],
    ['Burkina Faso', 'BFA'],
    ['Burundi', 'BDI'],
    ['Cambodge', 'KHM'],
    ['Cameroun', 'CMR'],
    ['Canada', 'CAN'],
    ['Cap-Vert', 'CPV'],
    ['Chili', 'CHL'],
    ['Chine', 'CHN'],
    ['Chypre', 'CYP'],
    ['Colombie', 'COL'],
    ['Comores', 'COM'],
    ['Congo-Brazzaville', 'COG'],
    ['Congo-Kinshasa', 'COD'],
    ['Corée du Nord', 'PRK'],
    ['Corée du Sud', 'KOR'],
    ['Costa Rica', 'CRI'],
    ['Côte d’Ivoire', 'CIV'],
    ['Croatie', 'HRV'],
    ['Cuba', 'CUB'],
    ['Danemark', 'DNK'],
    ['Djibouti', 'DJI'],
    ['Dominique', 'DMA'],
    ['Égypte', 'EGY'],
    ['Émirats arabes unis', 'ARE'],
    ['Équateur', 'ECU'],
    ['Érythrée', 'ERI'],
    ['Espagne', 'ESP'],
    ['Estonie', 'EST'],
    ['Eswatini', 'SWZ'],
    ['État de la Cité du Vatican', 'VAT'],
    ['États-Unis', 'USA'],
    ['Éthiopie', 'ETH'],
    ['Fidji', 'FJI'],
    ['Finlande', 'FIN'],
    ['France', 'FRA'],
    ['Gabon', 'GAB'],
    ['Gambie', 'GMB'],
    ['Géorgie', 'GEO'],
    ['Ghana', 'GHA'],
    ['Grèce', 'GRC'],
    ['Grenade', 'GRD'],
    ['Groenland', 'GRL'],
    ['Guatemala', 'GTM'],
    ['Guinée', 'GIN'],
    ['Guinée-Bissau', 'GNB'],
    ['Guinée équatoriale', 'GNQ'],
    ['Guyana', 'GUY'],
    ['Haïti', 'HTI'],
    ['Honduras', 'HND'],
    ['Hongrie', 'HUN'],
    ['Îles Malouines', 'FLK'],
    ['Îles Marshall', 'MHL'],
    ['Îles Salomon', 'SLB'],
    ['Inde', 'IND'],
    ['Indonésie', 'IDN'],
    ['Irak', 'IRQ'],
    ['Iran', 'IRN'],
    ['Irlande', 'IRL'],
    ['Islande', 'ISL'],
    ['Israël', 'ISR'],
    ['Italie', 'ITA'],
    ['Jamaïque', 'JAM'],
    ['Japon', 'JPN'],
    ['Jordanie', 'JOR'],
    ['Kazakhstan', 'KAZ'],
    ['Kenya', 'KEN'],
    ['Kirghizstan', 'KGZ'],
    ['Kiribati', 'KIR'],
    ['Kosovo', 'XKX'],
    ['Koweït', 'KWT'],
    ['Laos', 'LAO'],
    ['Lesotho', 'LSO'],
    ['Lettonie', 'LVA'],
    ['Liban', 'LBN'],
    ['Liberia', 'LBR'],
    ['Libye', 'LBY'],
    ['Liechtenstein', 'LIE'],
    ['Lituanie', 'LTU'],
    ['Luxembourg', 'LUX'],
    ['Macédoine du Nord', 'MKD'],
    ['Madagascar', 'MDG'],
    ['Malaisie', 'MYS'],
    ['Malawi', 'MWI'],
    ['Maldives', 'MDV'],
    ['Mali', 'MLI'],
    ['Malte', 'MLT'],
    ['Maroc', 'MAR'],
    ['Maurice', 'MUS'],
    ['Mauritanie', 'MRT'],
    ['Mexique', 'MEX'],
    ['Micronésie', 'FSM'],
    ['Moldavie', 'MDA'],
    ['Monaco', 'MCO'],
    ['Mongolie', 'MNG'],
    ['Monténégro', 'MNE'],
    ['Mozambique', 'MOZ'],
    ['Myanmar', 'MMR'],
    ['Myanmar (Birmanie)', 'MMR'],
    ['Namibie', 'NAM'],
    ['Nauru', 'NRU'],
    ['Népal', 'NPL'],
    ['Nicaragua', 'NIC'],
    ['Niger', 'NER'],
    ['Nigeria', 'NGA'],
    ['Norvège', 'NOR'],
    ['Nouvelle-Calédonie', 'NCL'],
    ['Nouvelle-Zélande', 'NZL'],
    ['Oman', 'OMN'],
    ['Ouganda', 'UGA'],
    ['Ouzbékistan', 'UZB'],
    ['Pakistan', 'PAK'],
    ['Palaos', 'PLW'],
    ['Panama', 'PAN'],
    ['Papouasie-Nouvelle-Guinée', 'PNG'],
    ['Paraguay', 'PRY'],
    ['Pays-Bas', 'NLD'],
    ['Pérou', 'PER'],
    ['Philippines', 'PHL'],
    ['Pologne', 'POL'],
    ['Porto Rico', 'PRI'],
    ['Portugal', 'PRT'],
    ['Qatar', 'QAT'],
    ['République centrafricaine', 'CAF'],
    ['République dominicaine', 'DOM'],
    ['Roumanie', 'ROU'],
    ['Royaume-Uni', 'GBR'],
    ['Russie', 'RUS'],
    ['Rwanda', 'RWA'],
    ['Sahara occidental', 'ESH'],
    ['Saint-Christophe-et-Niévès', 'KNA'],
    ['Saint-Marin', 'SMR'],
    ['Saint-Vincent-et-les Grenadines', 'VCT'],
    ['Sainte-Lucie', 'LCA'],
    ['Salvador', 'SLV'],
    ['Samoa', 'WSM'],
    ['Sao Tomé-et-Principe', 'STP'],
    ['Sénégal', 'SEN'],
    ['Serbie', 'SRB'],
    ['Seychelles', 'SYC'],
    ['Sierra Leone', 'SLE'],
    ['Singapour', 'SGP'],
    ['Slovaquie', 'SVK'],
    ['Slovénie', 'SVN'],
    ['Somalie', 'SOM'],
    ['Soudan', 'SDN'],
    ['Soudan du Sud', 'SSD'],
    ['Sri Lanka', 'LKA'],
    ['Suède', 'SWE'],
    ['Suisse', 'CHE'],
    ['Suriname', 'SUR'],
    ['Syrie', 'SYR'],
    ['Tadjikistan', 'TJK'],
    ['Taïwan', 'TWN'],
    ['Tanzanie', 'TZA'],
    ['Tchad', 'TCD'],
    ['Tchéquie', 'CZE'],
    ['Terres australes françaises', 'ATF'],
    ['Territoires palestiniens', 'PSE'],
    ['Thaïlande', 'THA'],
    ['Timor oriental', 'TLS'],
    ['Togo', 'TGO'],
    ['Tonga', 'TON'],
    ['Trinité-et-Tobago', 'TTO'],
    ['Tunisie', 'TUN'],
    ['Turkménistan', 'TKM'],
    ['Turquie', 'TUR'],
    ['Tuvalu', 'TUV'],
    ['Ukraine', 'UKR'],
    ['Uruguay', 'URY'],
    ['Vanuatu', 'VUT'],
    ['Venezuela', 'VEN'],
    ['Viêt Nam', 'VNM'],
    ['Yémen', 'YEM'],
    ['Zambie', 'ZMB'],
    ['Zimbabwe', 'ZWE'],
  ],
  de: [
    ['Afghanistan', 'AFG'],
    ['Ägypten', 'EGY'],
    ['Albanien', 'ALB'],
    ['Algerien', 'DZA'],
    ['Andorra', 'AND'],
    ['Angola', 'AGO'],
    ['Antarktis', 'ATA'],
    ['Antigua und Barbuda', 'ATG'],
    ['Äquatorialguinea', 'GNQ'],
    ['Argentinien', 'ARG'],
    ['Armenien', 'ARM'],
    ['Aserbaidschan', 'AZE'],
    ['Äthiopien', 'ETH'],
    ['Australien', 'AUS'],
    ['Bahamas', 'BHS'],
    ['Bahrain', 'BHR'],
    ['Bangladesch', 'BGD'],
    ['Barbados', 'BRB'],
    ['Belarus', 'BLR'],
    ['Belgien', 'BEL'],
    ['Belize', 'BLZ'],
    ['Benin', 'BEN'],
    ['Bhutan', 'BTN'],
    ['Bolivien', 'BOL'],
    ['Bosnien und Herzegowina', 'BIH'],
    ['Botsuana', 'BWA'],
    ['Brasilien', 'BRA'],
    ['Brunei Darussalam', 'BRN'],
    ['Bulgarien', 'BGR'],
    ['Burkina Faso', 'BFA'],
    ['Burundi', 'BDI'],
    ['Cabo Verde', 'CPV'],
    ['Chile', 'CHL'],
    ['China', 'CHN'],
    ['Costa Rica', 'CRI'],
    ['Côte d’Ivoire', 'CIV'],
    ['Dänemark', 'DNK'],
    ['Deutschland', 'DEU'],
    ['Dominica', 'DMA'],
    ['Dominikanische Republik', 'DOM'],
    ['Dschibuti', 'DJI'],
    ['Ecuador', 'ECU'],
    ['El Salvador', 'SLV'],
    ['Eritrea', 'ERI'],
    ['Estland', 'EST'],
    ['Eswatini', 'SWZ'],
    ['Falklandinseln', 'FLK'],
    ['Fidschi', 'FJI'],
    ['Finnland', 'FIN'],
    ['Frankreich', 'FRA'],
    ['Französische Süd- und Antarktisgebiete', 'ATF'],
    ['Gabun', 'GAB'],
    ['Gambia', 'GMB'],
    ['Georgien', 'GEO'],
    ['Ghana', 'GHA'],
    ['Grenada', 'GRD'],
    ['Griechenland', 'GRC'],
    ['Grönland', 'GRL'],
    ['Guatemala', 'GTM'],
    ['Guinea', 'GIN'],
    ['Guinea-Bissau', 'GNB'],
    ['Guyana', 'GUY'],
    ['Haiti', 'HTI'],
    ['Honduras', 'HND'],
    ['Indien', 'IND'],
    ['Indonesien', 'IDN'],
    ['Irak', 'IRQ'],
    ['Iran', 'IRN'],
    ['Irland', 'IRL'],
    ['Island', 'ISL'],
    ['Israel', 'ISR'],
    ['Italien', 'ITA'],
    ['Jamaika', 'JAM'],
    ['Japan', 'JPN'],
    ['Jemen', 'YEM'],
    ['Jordanien', 'JOR'],
    ['Kambodscha', 'KHM'],
    ['Kamerun', 'CMR'],
    ['Kanada', 'CAN'],
    ['Kasachstan', 'KAZ'],
    ['Katar', 'QAT'],
    ['Kenia', 'KEN'],
    ['Kirgisistan', 'KGZ'],
    ['Kiribati', 'KIR'],
    ['Kolumbien', 'COL'],
    ['Komoren', 'COM'],
    ['Kongo-Brazzaville', 'COG'],
    ['Kongo-Kinshasa', 'COD'],
    ['Kosovo', 'XKX'],
    ['Kroatien', 'HRV'],
    ['Kuba', 'CUB'],
    ['Kuwait', 'KWT'],
    ['Laos', 'LAO'],
    ['Lesotho', 'LSO'],
    ['Lettland', 'LVA'],
    ['Libanon', 'LBN'],
    ['Liberia', 'LBR'],
    ['Libyen', 'LBY'],
    ['Liechtenstein', 'LIE'],
    ['Litauen', 'LTU'],
    ['Luxemburg', 'LUX'],
    ['Madagaskar', 'MDG'],
    ['Malawi', 'MWI'],
    ['Malaysia', 'MYS'],
    ['Malediven', 'MDV'],
    ['Mali', 'MLI'],
    ['Malta', 'MLT'],
    ['Marokko', 'MAR'],
    ['Marshallinseln', 'MHL'],
    ['Mauretanien', 'MRT'],
    ['Mauritius', 'MUS'],
    ['Mexiko', 'MEX'],
    ['Mikronesien', 'FSM'],
    ['Monaco', 'MCO'],
    ['Mongolei', 'MNG'],
    ['Montenegro', 'MNE'],
    ['Mosambik', 'MOZ'],
    ['Myanmar', 'MMR'],
    ['Namibia', 'NAM'],
    ['Nauru', 'NRU'],
    ['Nepal', 'NPL'],
    ['Neukaledonien', 'NCL'],
    ['Neuseeland', 'NZL'],
    ['Nicaragua', 'NIC'],
    ['Niederlande', 'NLD'],
    ['Niger', 'NER'],
    ['Nigeria', 'NGA'],
    ['Nordkorea', 'PRK'],
    ['Nordmazedonien', 'MKD'],
    ['Norwegen', 'NOR'],
    ['Oman', 'OMN'],
    ['Österreich', 'AUT'],
    ['Pakistan', 'PAK'],
    ['Palästinensische Autonomiegebiete', 'PSE'],
    ['Palau', 'PLW'],
    ['Panama', 'PAN'],
    ['Papua-Neuguinea', 'PNG'],
    ['Paraguay', 'PRY'],
    ['Peru', 'PER'],
    ['Philippinen', 'PHL'],
    ['Polen', 'POL'],
    ['Portugal', 'PRT'],
    ['Puerto Rico', 'PRI'],
    ['Republik Moldau', 'MDA'],
    ['Ruanda', 'RWA'],
    ['Rumänien', 'ROU'],
    ['Russland', 'RUS'],
    ['Salomonen', 'SLB'],
    ['Sambia', 'ZMB'],
    ['Samoa', 'WSM'],
    ['San Marino', 'SMR'],
    ['São Tomé und Príncipe', 'STP'],
    ['Saudi-Arabien', 'SAU'],
    ['Schweden', 'SWE'],
    ['Schweiz', 'CHE'],
    ['Senegal', 'SEN'],
    ['Serbien', 'SRB'],
    ['Seychellen', 'SYC'],
    ['Sierra Leone', 'SLE'],
    ['Simbabwe', 'ZWE'],
    ['Singapur', 'SGP'],
    ['Slowakei', 'SVK'],
    ['Slowenien', 'SVN'],
    ['Somalia', 'SOM'],
    ['Spanien', 'ESP'],
    ['Sri Lanka', 'LKA'],
    ['St. Kitts und Nevis', 'KNA'],
    ['St. Lucia', 'LCA'],
    ['St. Vincent und die Grenadinen', 'VCT'],
    ['Südafrika', 'ZAF'],
    ['Sudan', 'SDN'],
    ['Südkorea', 'KOR'],
    ['Südsudan', 'SSD'],
    ['Suriname', 'SUR'],
    ['Syrien', 'SYR'],
    ['Tadschikistan', 'TJK'],
    ['Taiwan', 'TWN'],
    ['Tansania', 'TZA'],
    ['Thailand', 'THA'],
    ['Timor-Leste', 'TLS'],
    ['Togo', 'TGO'],
    ['Tonga', 'TON'],
    ['Trinidad und Tobago', 'TTO'],
    ['Tschad', 'TCD'],
    ['Tschechien', 'CZE'],
    ['Tunesien', 'TUN'],
    ['Türkei', 'TUR'],
    ['Turkmenistan', 'TKM'],
    ['Tuvalu', 'TUV'],
    ['Uganda', 'UGA'],
    ['Ukraine', 'UKR'],
    ['Ungarn', 'HUN'],
    ['Uruguay', 'URY'],
    ['Usbekistan', 'UZB'],
    ['Vanuatu', 'VUT'],
    ['Vatikanstadt', 'VAT'],
    ['Venezuela', 'VEN'],
    ['Vereinigte Arabische Emirate', 'ARE'],
    ['Vereinigte Staaten', 'USA'],
    ['Vereinigtes Königreich', 'GBR'],
    ['Vietnam', 'VNM'],
    ['Westsahara', 'ESH'],
    ['Zentralafrikanische Republik', 'CAF'],
    ['Zypern', 'CYP'],
  ],
  es: [
    ['Afganistán', 'AFG'],
    ['Albania', 'ALB'],
    ['Alemania', 'DEU'],
    ['Andorra', 'AND'],
    ['Angola', 'AGO'],
    ['Antártida', 'ATA'],
    ['Antigua y Barbuda', 'ATG'],
    ['Arabia Saudí', 'SAU'],
    ['Argelia', 'DZA'],
    ['Argentina', 'ARG'],
    ['Armenia', 'ARM'],
    ['Australia', 'AUS'],
    ['Austria', 'AUT'],
    ['Azerbaiyán', 'AZE'],
    ['Bahamas', 'BHS'],
    ['Bangladés', 'BGD'],
    ['Barbados', 'BRB'],
    ['Baréin', 'BHR'],
    ['Bélgica', 'BEL'],
    ['Belice', 'BLZ'],
    ['Benín', 'BEN'],
    ['Bielorrusia', 'BLR'],
    ['Birmania', 'MMR'],
    ['Bolivia', 'BOL'],
    ['Bosnia y Herzegovina', 'BIH'],
    ['Botsuana', 'BWA'],
    ['Brasil', 'BRA'],
    ['Brunéi', 'BRN'],
    ['Bulgaria', 'BGR'],
    ['Burkina Faso', 'BFA'],
    ['Burundi', 'BDI'],
    ['Bután', 'BTN'],
    ['Cabo Verde', 'CPV'],
    ['Camboya', 'KHM'],
    ['Camerún', 'CMR'],
    ['Canadá', 'CAN'],
    ['Catar', 'QAT'],
    ['Chad', 'TCD'],
    ['Chequia', 'CZE'],
    ['Chile', 'CHL'],
    ['China', 'CHN'],
    ['Chipre', 'CYP'],
    ['Ciudad del Vaticano', 'VAT'],
    ['Colombia', 'COL'],
    ['Comoras', 'COM'],
    ['Congo', 'COG'],
    ['Corea del Norte', 'PRK'],
    ['Corea del Sur', 'KOR'],
    ['Costa Rica', 'CRI'],
    ['Côte d’Ivoire', 'CIV'],
    ['Croacia', 'HRV'],
    ['Cuba', 'CUB'],
    ['Dinamarca', 'DNK'],
    ['Dominica', 'DMA'],
    ['Ecuador', 'ECU'],
    ['Egipto', 'EGY'],
    ['El Salvador', 'SLV'],
    ['Emiratos Árabes Unidos', 'ARE'],
    ['Eritrea', 'ERI'],
    ['Eslovaquia', 'SVK'],
    ['Eslovenia', 'SVN'],
    ['España', 'ESP'],
    ['Estados Unidos', 'USA'],
    ['Estonia', 'EST'],
    ['Esuatini', 'SWZ'],
    ['Etiopía', 'ETH'],
    ['Filipinas', 'PHL'],
    ['Finlandia', 'FIN'],
    ['Fiyi', 'FJI'],
    ['Francia', 'FRA'],
    ['Gabón', 'GAB'],
    ['Gambia', 'GMB'],
    ['Georgia', 'GEO'],
    ['Ghana', 'GHA'],
    ['Granada', 'GRD'],
    ['Grecia', 'GRC'],
    ['Groenlandia', 'GRL'],
    ['Guatemala', 'GTM'],
    ['Guinea', 'GIN'],
    ['Guinea-Bisáu', 'GNB'],
    ['Guinea Ecuatorial', 'GNQ'],
    ['Guyana', 'GUY'],
    ['Haití', 'HTI'],
    ['Honduras', 'HND'],
    ['Hungría', 'HUN'],
    ['India', 'IND'],
    ['Indonesia', 'IDN'],
    ['Irak', 'IRQ'],
    ['Irán', 'IRN'],
    ['Irlanda', 'IRL'],
    ['Islandia', 'ISL'],
    ['Islas Malvinas', 'FLK'],
    ['Islas Marshall', 'MHL'],
    ['Islas Salomón', 'SLB'],
    ['Israel', 'ISR'],
    ['Italia', 'ITA'],
    ['Jamaica', 'JAM'],
    ['Japón', 'JPN'],
    ['Jordania', 'JOR'],
    ['Kazajistán', 'KAZ'],
    ['Kenia', 'KEN'],
    ['Kirguistán', 'KGZ'],
    ['Kiribati', 'KIR'],
    ['Kosovo', 'XKX'],
    ['Kuwait', 'KWT'],
    ['Laos', 'LAO'],
    ['Lesoto', 'LSO'],
    ['Letonia', 'LVA'],
    ['Líbano', 'LBN'],
    ['Liberia', 'LBR'],
    ['Libia', 'LBY'],
    ['Liechtenstein', 'LIE'],
    ['Lituania', 'LTU'],
    ['Luxemburgo', 'LUX'],
    ['Macedonia del Norte', 'MKD'],
    ['Madagascar', 'MDG'],
    ['Malasia', 'MYS'],
    ['Malaui', 'MWI'],
    ['Maldivas', 'MDV'],
    ['Mali', 'MLI'],
    ['Malta', 'MLT'],
    ['Marruecos', 'MAR'],
    ['Mauricio', 'MUS'],
    ['Mauritania', 'MRT'],
    ['México', 'MEX'],
    ['Micronesia', 'FSM'],
    ['Moldavia', 'MDA'],
    ['Mónaco', 'MCO'],
    ['Mongolia', 'MNG'],
    ['Montenegro', 'MNE'],
    ['Mozambique', 'MOZ'],
    ['Myanmar', 'MMR'],
    ['Myanmar (Birmania)', 'MMR'],
    ['Namibia', 'NAM'],
    ['Nauru', 'NRU'],
    ['Nepal', 'NPL'],
    ['Nicaragua', 'NIC'],
    ['Níger', 'NER'],
    ['Nigeria', 'NGA'],
    ['Noruega', 'NOR'],
    ['Nueva Caledonia', 'NCL'],
    ['Nueva Zelanda', 'NZL'],
    ['Omán', 'OMN'],
    ['Países Bajos', 'NLD'],
    ['Pakistán', 'PAK'],
    ['Palaos', 'PLW'],
    ['Panamá', 'PAN'],
    ['Papúa Nueva Guinea', 'PNG'],
    ['Paraguay', 'PRY'],
    ['Perú', 'PER'],
    ['Polonia', 'POL'],
    ['Portugal', 'PRT'],
    ['Puerto Rico', 'PRI'],
    ['Reino Unido', 'GBR'],
    ['República Centroafricana', 'CAF'],
    ['República Democrática del Congo', 'COD'],
    ['República Dominicana', 'DOM'],
    ['Ruanda', 'RWA'],
    ['Rumanía', 'ROU'],
    ['Rusia', 'RUS'],
    ['Sáhara Occidental', 'ESH'],
    ['Samoa', 'WSM'],
    ['San Cristóbal y Nieves', 'KNA'],
    ['San Marino', 'SMR'],
    ['San Vicente y las Granadinas', 'VCT'],
    ['Santa Lucía', 'LCA'],
    ['Santo Tomé y Príncipe', 'STP'],
    ['Senegal', 'SEN'],
    ['Serbia', 'SRB'],
    ['Seychelles', 'SYC'],
    ['Sierra Leona', 'SLE'],
    ['Singapur', 'SGP'],
    ['Siria', 'SYR'],
    ['Somalia', 'SOM'],
    ['Sri Lanka', 'LKA'],
    ['Sudáfrica', 'ZAF'],
    ['Sudán', 'SDN'],
    ['Sudán del Sur', 'SSD'],
    ['Suecia', 'SWE'],
    ['Suiza', 'CHE'],
    ['Surinam', 'SUR'],
    ['Tailandia', 'THA'],
    ['Taiwán', 'TWN'],
    ['Tanzania', 'TZA'],
    ['Tayikistán', 'TJK'],
    ['Territorios Australes Franceses', 'ATF'],
    ['Territorios Palestinos', 'PSE'],
    ['Timor-Leste', 'TLS'],
    ['Togo', 'TGO'],
    ['Tonga', 'TON'],
    ['Trinidad y Tobago', 'TTO'],
    ['Túnez', 'TUN'],
    ['Turkmenistán', 'TKM'],
    ['Turquía', 'TUR'],
    ['Tuvalu', 'TUV'],
    ['Ucrania', 'UKR'],
    ['Uganda', 'UGA'],
    ['Uruguay', 'URY'],
    ['Uzbekistán', 'UZB'],
    ['Vanuatu', 'VUT'],
    ['Venezuela', 'VEN'],
    ['Vietnam', 'VNM'],
    ['Yemen', 'YEM'],
    ['Yibuti', 'DJI'],
    ['Zambia', 'ZMB'],
    ['Zimbabue', 'ZWE'],
  ],
  pt: [
    ['Afeganistão', 'AFG'],
    ['África do Sul', 'ZAF'],
    ['Albânia', 'ALB'],
    ['Alemanha', 'DEU'],
    ['Andorra', 'AND'],
    ['Angola', 'AGO'],
    ['Antártida', 'ATA'],
    ['Antígua e Barbuda', 'ATG'],
    ['Arábia Saudita', 'SAU'],
    ['Argélia', 'DZA'],
    ['Argentina', 'ARG'],
    ['Armênia', 'ARM'],
    ['Austrália', 'AUS'],
    ['Áustria', 'AUT'],
    ['Azerbaijão', 'AZE'],
    ['Bahamas', 'BHS'],
    ['Bangladesh', 'BGD'],
    ['Barbados', 'BRB'],
    ['Barein', 'BHR'],
    ['Bélgica', 'BEL'],
    ['Belize', 'BLZ'],
    ['Benin', 'BEN'],
    ['Bielorrússia', 'BLR'],
    ['Birmânia', 'MMR'],
    ['Bolívia', 'BOL'],
    ['Bósnia e Herzegovina', 'BIH'],
    ['Botsuana', 'BWA'],
    ['Brasil', 'BRA'],
    ['Brunei', 'BRN'],
    ['Bulgária', 'BGR'],
    ['Burquina Faso', 'BFA'],
    ['Burundi', 'BDI'],
    ['Butão', 'BTN'],
    ['Cabo Verde', 'CPV'],
    ['Camarões', 'CMR'],
    ['Camboja', 'KHM'],
    ['Canadá', 'CAN'],
    ['Catar', 'QAT'],
    ['Cazaquistão', 'KAZ'],
    ['Chade', 'TCD'],
    ['Chile', 'CHL'],
    ['China', 'CHN'],
    ['Chipre', 'CYP'],
    ['Cidade do Vaticano', 'VAT'],
    ['Colômbia', 'COL'],
    ['Comores', 'COM'],
    ['Congo - Kinshasa', 'COD'],
    ['Coreia do Norte', 'PRK'],
    ['Coreia do Sul', 'KOR'],
    ['Costa do Marfim', 'CIV'],
    ['Costa Rica', 'CRI'],
    ['Croácia', 'HRV'],
    ['Cuba', 'CUB'],
    ['Dinamarca', 'DNK'],
    ['Djibuti', 'DJI'],
    ['Dominica', 'DMA'],
    ['Egito', 'EGY'],
    ['El Salvador', 'SLV'],
    ['Emirados Árabes Unidos', 'ARE'],
    ['Equador', 'ECU'],
    ['Eritreia', 'ERI'],
    ['Eslováquia', 'SVK'],
    ['Eslovênia', 'SVN'],
    ['Espanha', 'ESP'],
    ['Essuatíni', 'SWZ'],
    ['Estados Unidos', 'USA'],
    ['Estônia', 'EST'],
    ['Etiópia', 'ETH'],
    ['Fiji', 'FJI'],
    ['Filipinas', 'PHL'],
    ['Finlândia', 'FIN'],
    ['França', 'FRA'],
    ['Gabão', 'GAB'],
    ['Gâmbia', 'GMB'],
    ['Gana', 'GHA'],
    ['Geórgia', 'GEO'],
    ['Granada', 'GRD'],
    ['Grécia', 'GRC'],
    ['Groenlândia', 'GRL'],
    ['Guatemala', 'GTM'],
    ['Guiana', 'GUY'],
    ['Guiné', 'GIN'],
    ['Guiné-Bissau', 'GNB'],
    ['Guiné Equatorial', 'GNQ'],
    ['Haiti', 'HTI'],
    ['Honduras', 'HND'],
    ['Hungria', 'HUN'],
    ['Iêmen', 'YEM'],
    ['Ilhas Malvinas', 'FLK'],
    ['Ilhas Marshall', 'MHL'],
    ['Ilhas Salomão', 'SLB'],
    ['Índia', 'IND'],
    ['Indonésia', 'IDN'],
    ['Irã', 'IRN'],
    ['Iraque', 'IRQ'],
    ['Irlanda', 'IRL'],
    ['Islândia', 'ISL'],
    ['Israel', 'ISR'],
    ['Itália', 'ITA'],
    ['Jamaica', 'JAM'],
    ['Japão', 'JPN'],
    ['Jordânia', 'JOR'],
    ['Kosovo', 'XKX'],
    ['Kuwait', 'KWT'],
    ['Laos', 'LAO'],
    ['Lesoto', 'LSO'],
    ['Letônia', 'LVA'],
    ['Líbano', 'LBN'],
    ['Libéria', 'LBR'],
    ['Líbia', 'LBY'],
    ['Liechtenstein', 'LIE'],
    ['Lituânia', 'LTU'],
    ['Luxemburgo', 'LUX'],
    ['Macedônia do Norte', 'MKD'],
    ['Madagascar', 'MDG'],
    ['Malásia', 'MYS'],
    ['Malaui', 'MWI'],
    ['Maldivas', 'MDV'],
    ['Mali', 'MLI'],
    ['Malta', 'MLT'],
    ['Marrocos', 'MAR'],
    ['Maurício', 'MUS'],
    ['Mauritânia', 'MRT'],
    ['México', 'MEX'],
    ['Mianmar', 'MMR'],
    ['Mianmar (Birmânia)', 'MMR'],
    ['Micronésia', 'FSM'],
    ['Moçambique', 'MOZ'],
    ['Moldávia', 'MDA'],
    ['Mônaco', 'MCO'],
    ['Mongólia', 'MNG'],
    ['Montenegro', 'MNE'],
    ['Namíbia', 'NAM'],
    ['Nauru', 'NRU'],
    ['Nepal', 'NPL'],
    ['Nicarágua', 'NIC'],
    ['Níger', 'NER'],
    ['Nigéria', 'NGA'],
    ['Noruega', 'NOR'],
    ['Nova Caledônia', 'NCL'],
    ['Nova Zelândia', 'NZL'],
    ['Omã', 'OMN'],
    ['Países Baixos', 'NLD'],
    ['Palau', 'PLW'],
    ['Panamá', 'PAN'],
    ['Papua-Nova Guiné', 'PNG'],
    ['Paquistão', 'PAK'],
    ['Paraguai', 'PRY'],
    ['Peru', 'PER'],
    ['Polônia', 'POL'],
    ['Porto Rico', 'PRI'],
    ['Portugal', 'PRT'],
    ['Quênia', 'KEN'],
    ['Quirguistão', 'KGZ'],
    ['Quiribati', 'KIR'],
    ['Reino Unido', 'GBR'],
    ['República Centro-Africana', 'CAF'],
    ['República do Congo', 'COG'],
    ['República Dominicana', 'DOM'],
    ['Romênia', 'ROU'],
    ['Ruanda', 'RWA'],
    ['Rússia', 'RUS'],
    ['Saara Ocidental', 'ESH'],
    ['Samoa', 'WSM'],
    ['San Marino', 'SMR'],
    ['Santa Lúcia', 'LCA'],
    ['São Cristóvão e Névis', 'KNA'],
    ['São Tomé e Príncipe', 'STP'],
    ['São Vicente e Granadinas', 'VCT'],
    ['Seicheles', 'SYC'],
    ['Senegal', 'SEN'],
    ['Serra Leoa', 'SLE'],
    ['Sérvia', 'SRB'],
    ['Singapura', 'SGP'],
    ['Síria', 'SYR'],
    ['Somália', 'SOM'],
    ['Sri Lanka', 'LKA'],
    ['Sudão', 'SDN'],
    ['Sudão do Sul', 'SSD'],
    ['Suécia', 'SWE'],
    ['Suíça', 'CHE'],
    ['Suriname', 'SUR'],
    ['Tadjiquistão', 'TJK'],
    ['Tailândia', 'THA'],
    ['Taiwan', 'TWN'],
    ['Tanzânia', 'TZA'],
    ['Tchéquia', 'CZE'],
    ['Territórios Franceses do Sul', 'ATF'],
    ['Territórios palestinos', 'PSE'],
    ['Timor-Leste', 'TLS'],
    ['Togo', 'TGO'],
    ['Tonga', 'TON'],
    ['Trinidad e Tobago', 'TTO'],
    ['Tunísia', 'TUN'],
    ['Turcomenistão', 'TKM'],
    ['Turquia', 'TUR'],
    ['Tuvalu', 'TUV'],
    ['Ucrânia', 'UKR'],
    ['Uganda', 'UGA'],
    ['Uruguai', 'URY'],
    ['Uzbequistão', 'UZB'],
    ['Vanuatu', 'VUT'],
    ['Venezuela', 'VEN'],
    ['Vietnã', 'VNM'],
    ['Zâmbia', 'ZMB'],
    ['Zimbábue', 'ZWE'],
  ],
  ar: [
    ['إثيوبيا', 'ETH'],
    ['أذربيجان', 'AZE'],
    ['أرمينيا', 'ARM'],
    ['إريتريا', 'ERI'],
    ['إسبانيا', 'ESP'],
    ['أستراليا', 'AUS'],
    ['إستونيا', 'EST'],
    ['إسرائيل', 'ISR'],
    ['إسواتيني', 'SWZ'],
    ['أفغانستان', 'AFG'],
    ['الأراضي الفلسطينية', 'PSE'],
    ['الأرجنتين', 'ARG'],
    ['الأردن', 'JOR'],
    ['الأقاليم الجنوبية الفرنسية', 'ATF'],
    ['الإكوادور', 'ECU'],
    ['الإمارات العربية المتحدة', 'ARE'],
    ['ألبانيا', 'ALB'],
    ['البحرين', 'BHR'],
    ['البرازيل', 'BRA'],
    ['البرتغال', 'PRT'],
    ['البوسنة والهرسك', 'BIH'],
    ['التشيك', 'CZE'],
    ['الجبل الأسود', 'MNE'],
    ['الجزائر', 'DZA'],
    ['الدانمرك', 'DNK'],
    ['الرأس الأخضر', 'CPV'],
    ['السلفادور', 'SLV'],
    ['السنغال', 'SEN'],
    ['السودان', 'SDN'],
    ['السويد', 'SWE'],
    ['الصحراء الغربية', 'ESH'],
    ['الصومال', 'SOM'],
    ['الصين', 'CHN'],
    ['العراق', 'IRQ'],
    ['الغابون', 'GAB'],
    ['الفاتيكان', 'VAT'],
    ['الفلبين', 'PHL'],
    ['الكاميرون', 'CMR'],
    ['الكونغو - برازافيل', 'COG'],
    ['الكونغو - كينشاسا', 'COD'],
    ['الكويت', 'KWT'],
    ['ألمانيا', 'DEU'],
    ['المغرب', 'MAR'],
    ['المكسيك', 'MEX'],
    ['المملكة العربية السعودية', 'SAU'],
    ['المملكة المتحدة', 'GBR'],
    ['النرويج', 'NOR'],
    ['النمسا', 'AUT'],
    ['النيجر', 'NER'],
    ['الهند', 'IND'],
    ['الولايات المتحدة', 'USA'],
    ['اليابان', 'JPN'],
    ['اليمن', 'YEM'],
    ['اليونان', 'GRC'],
    ['أنتاركتيكا', 'ATA'],
    ['أنتيغوا وبربودا', 'ATG'],
    ['أندورا', 'AND'],
    ['إندونيسيا', 'IDN'],
    ['أنغولا', 'AGO'],
    ['أورغواي', 'URY'],
    ['أوزبكستان', 'UZB'],
    ['أوغندا', 'UGA'],
    ['أوكرانيا', 'UKR'],
    ['إيران', 'IRN'],
    ['أيرلندا', 'IRL'],
    ['آيسلندا', 'ISL'],
    ['إيطاليا', 'ITA'],
    ['بابوا غينيا الجديدة', 'PNG'],
    ['باراغواي', 'PRY'],
    ['باكستان', 'PAK'],
    ['بالاو', 'PLW'],
    ['بربادوس', 'BRB'],
    ['بروناي', 'BRN'],
    ['بلجيكا', 'BEL'],
    ['بلغاريا', 'BGR'],
    ['بليز', 'BLZ'],
    ['بنغلاديش', 'BGD'],
    ['بنما', 'PAN'],
    ['بنين', 'BEN'],
    ['بوتان', 'BTN'],
    ['بوتسوانا', 'BWA'],
    ['بورتوريكو', 'PRI'],
    ['بوركينا فاسو', 'BFA'],
    ['بورما', 'MMR'],
    ['بوروندي', 'BDI'],
    ['بولندا', 'POL'],
    ['بوليفيا', 'BOL'],
    ['بيرو', 'PER'],
    ['بيلاروس', 'BLR'],
    ['تايلاند', 'THA'],
    ['تايوان', 'TWN'],
    ['تركمانستان', 'TKM'],
    ['تركيا', 'TUR'],
    ['ترينيداد وتوباغو', 'TTO'],
    ['تشاد', 'TCD'],
    ['تشيلي', 'CHL'],
    ['تنزانيا', 'TZA'],
    ['توغو', 'TGO'],
    ['توفالو', 'TUV'],
    ['تونس', 'TUN'],
    ['تونغا', 'TON'],
    ['تيمور - ليشتي', 'TLS'],
    ['جامايكا', 'JAM'],
    ['جزر البهاما', 'BHS'],
    ['جزر القمر', 'COM'],
    ['جزر المالديف', 'MDV'],
    ['جزر سليمان', 'SLB'],
    ['جزر فوكلاند', 'FLK'],
    ['جزر مارشال', 'MHL'],
    ['جمهورية أفريقيا الوسطى', 'CAF'],
    ['جمهورية الدومينيكان', 'DOM'],
    ['جنوب أفريقيا', 'ZAF'],
    ['جنوب السودان', 'SSD'],
    ['جورجيا', 'GEO'],
    ['جيبوتي', 'DJI'],
    ['دومينيكا', 'DMA'],
    ['رواندا', 'RWA'],
    ['روسيا', 'RUS'],
    ['رومانيا', 'ROU'],
    ['زامبيا', 'ZMB'],
    ['زيمبابوي', 'ZWE'],
    ['ساحل العاج', 'CIV'],
    ['ساموا', 'WSM'],
    ['سان مارينو', 'SMR'],
    ['سانت فنسنت وجزر غرينادين', 'VCT'],
    ['سانت كيتس ونيفيس', 'KNA'],
    ['سانت لوسيا', 'LCA'],
    ['ساو تومي وبرينسيبي', 'STP'],
    ['سريلانكا', 'LKA'],
    ['سلوفاكيا', 'SVK'],
    ['سلوفينيا', 'SVN'],
    ['سنغافورة', 'SGP'],
    ['سوريا', 'SYR'],
    ['سورينام', 'SUR'],
    ['سويسرا', 'CHE'],
    ['سيراليون', 'SLE'],
    ['سيشل', 'SYC'],
    ['صربيا', 'SRB'],
    ['طاجيكستان', 'TJK'],
    ['عُمان', 'OMN'],
    ['غامبيا', 'GMB'],
    ['غانا', 'GHA'],
    ['غرينادا', 'GRD'],
    ['غرينلاند', 'GRL'],
    ['غواتيمالا', 'GTM'],
    ['غيانا', 'GUY'],
    ['غينيا', 'GIN'],
    ['غينيا الاستوائية', 'GNQ'],
    ['غينيا بيساو', 'GNB'],
    ['فانواتو', 'VUT'],
    ['فرنسا', 'FRA'],
    ['فنزويلا', 'VEN'],
    ['فنلندا', 'FIN'],
    ['فيتنام', 'VNM'],
    ['فيجي', 'FJI'],
    ['قبرص', 'CYP'],
    ['قطر', 'QAT'],
    ['قيرغيزستان', 'KGZ'],
    ['كازاخستان', 'KAZ'],
    ['كاليدونيا الجديدة', 'NCL'],
    ['كرواتيا', 'HRV'],
    ['كمبوديا', 'KHM'],
    ['كندا', 'CAN'],
    ['كوبا', 'CUB'],
    ['كوريا الجنوبية', 'KOR'],
    ['كوريا الشمالية', 'PRK'],
    ['كوستاريكا', 'CRI'],
    ['كوسوفو', 'XKX'],
    ['كولومبيا', 'COL'],
    ['كيريباتي', 'KIR'],
    ['كينيا', 'KEN'],
    ['لاتفيا', 'LVA'],
    ['لاوس', 'LAO'],
    ['لبنان', 'LBN'],
    ['لوكسمبورغ', 'LUX'],
    ['ليبيا', 'LBY'],
    ['ليبيريا', 'LBR'],
    ['ليتوانيا', 'LTU'],
    ['ليختنشتاين', 'LIE'],
    ['ليسوتو', 'LSO'],
    ['مالطا', 'MLT'],
    ['مالي', 'MLI'],
    ['ماليزيا', 'MYS'],
    ['مدغشقر', 'MDG'],
    ['مصر', 'EGY'],
    ['مقدونيا الشمالية', 'MKD'],
    ['ملاوي', 'MWI'],
    ['منغوليا', 'MNG'],
    ['موريتانيا', 'MRT'],
    ['موريشيوس', 'MUS'],
    ['موزمبيق', 'MOZ'],
    ['مولدوفا', 'MDA'],
    ['موناكو', 'MCO'],
    ['ميانمار', 'MMR'],
    ['ميانمار (بورما)', 'MMR'],
    ['ميكرونيزيا', 'FSM'],
    ['ناميبيا', 'NAM'],
    ['ناورو', 'NRU'],
    ['نيبال', 'NPL'],
    ['نيجيريا', 'NGA'],
    ['نيكاراغوا', 'NIC'],
    ['نيوزيلندا', 'NZL'],
    ['هايتي', 'HTI'],
    ['هندوراس', 'HND'],
    ['هنغاريا', 'HUN'],
    ['هولندا', 'NLD'],
  ],
};
