/** Existing product-governed memberships, shared by map and source accounting. */
export const MIDDLE_EAST_MEMBERS: readonly string[] = Object.freeze([
  'BHR',
  'EGY',
  'IRN',
  'IRQ',
  'ISR',
  'JOR',
  'KWT',
  'LBN',
  'OMN',
  'PSE',
  'QAT',
  'SAU',
  'SYR',
  'TUR',
  'ARE',
  'YEM',
]);
export const EAST_AFRICA_MEMBERS: readonly string[] = Object.freeze([
  'BDI',
  'COD',
  'DJI',
  'ERI',
  'ETH',
  'KEN',
  'RWA',
  'SOM',
  'SSD',
  'TZA',
  'UGA',
]);
