-- ════════════════════════════════════════════════════════════════════════════
-- ADMIN ASK INTELLIGENCE OBSERVABILITY R1 — ASK OBSERVATION STORE
-- ════════════════════════════════════════════════════════════════════════════
-- Authority: CTO ADMIN ASK INTELLIGENCE OBSERVABILITY R1 (Product Owner authorized for
-- Alpha development). Base: 5bd925de95cfe9fca2c9a97cddc88c249d751564.
--
-- CLASS: ADDITIVE — two new tables and four indexes. No existing table is altered,
-- dropped or renamed; no column is added to an existing table; there is no foreign key
-- to any existing table, so this cannot cascade a delete anywhere and cannot lock an
-- existing table beyond the catalog.
--
-- NOT GENERATED BY `prisma migrate diff`, AND THAT IS DISCLOSED RATHER THAN HIDDEN.
-- `binaries.prisma.sh` is refused by this session's egress policy (403 at CONNECT), so
-- the schema engine that `migrate diff` needs could not be obtained. This file is
-- hand-authored from the two model blocks and then PROVEN equivalent: the R1 migration
-- spec applies every migration in order to a real PostgreSQL 16 instance and asserts the
-- resulting columns, types, nullability and indexes against the schema, and the live
-- observation spec then reads and writes both tables through the generated Prisma client.
-- A hand-authored file that a client round-trips against is checked; one that is merely
-- read is not.
--
-- APPLIED: never, outside the loopback test cluster this branch was validated on.
-- Applying to Alpha is a separate Product Owner authorisation.

-- CreateTable
CREATE TABLE "AskObservation" (
    "id" TEXT NOT NULL,
    "operationId" TEXT NOT NULL,
    "occurredAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "schemaVersion" TEXT NOT NULL,
    "routePath" TEXT NOT NULL,
    "adapterVersion" TEXT NOT NULL,
    "questionClass" TEXT NOT NULL,
    "queryIntent" TEXT NOT NULL,
    "terminalState" TEXT NOT NULL,
    "answerState" TEXT NOT NULL,
    "answerBasis" TEXT NOT NULL,
    "clarificationRequired" BOOLEAN NOT NULL DEFAULT false,
    "capabilityUnavailable" BOOLEAN NOT NULL DEFAULT false,
    "refusalCodes" TEXT[],
    "disclosureCodes" TEXT[],
    "clarificationCodes" TEXT[],
    "requestLanguage" TEXT NOT NULL,
    "questionLanguage" TEXT,
    "languageClassification" TEXT NOT NULL,
    "normalizationStatus" TEXT NOT NULL,
    "geographyPresent" BOOLEAN NOT NULL DEFAULT false,
    "geographyCodes" TEXT[],
    "geographySources" TEXT[],
    "geographyPrecision" TEXT NOT NULL,
    "geographyCodesDropped" INTEGER NOT NULL DEFAULT 0,
    "scopedBy" TEXT NOT NULL,
    "domains" TEXT[],
    "domainCount" INTEGER NOT NULL DEFAULT 0,
    "topicPresent" BOOLEAN NOT NULL DEFAULT false,
    "temporalRequirement" TEXT NOT NULL,
    "statedPeriodPresent" BOOLEAN NOT NULL DEFAULT false,
    "evidenceRolesRequested" TEXT[],
    "evidenceRolesObtained" TEXT[],
    "evidenceRolesMissing" TEXT[],
    "reportingItemCount" INTEGER,
    "computeClass" TEXT NOT NULL,
    "providerId" TEXT,
    "providerCallCount" INTEGER NOT NULL DEFAULT 0,
    "modelInvocationCount" INTEGER NOT NULL DEFAULT 0,
    "aiExecuted" BOOLEAN NOT NULL DEFAULT false,
    "breakerOutcome" TEXT,
    "promptTokens" INTEGER,
    "completionTokens" INTEGER,
    "tokensMeasured" BOOLEAN NOT NULL DEFAULT false,
    "latencyMs" INTEGER,
    "failureCode" TEXT,
    "identityState" TEXT NOT NULL,
    "askR2Enabled" BOOLEAN,
    "askPublicComputeEnabled" BOOLEAN,

    CONSTRAINT "AskObservation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AskAccessCounter" (
    "event" TEXT NOT NULL,
    "bucketStart" TIMESTAMPTZ(6) NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "AskAccessCounter_pkey" PRIMARY KEY ("event","bucketStart")
);

-- CreateIndex
CREATE UNIQUE INDEX "AskObservation_operationId_key" ON "AskObservation"("operationId");

-- CreateIndex
CREATE INDEX "AskObservation_occurredAt_idx" ON "AskObservation"("occurredAt");

-- CreateIndex
CREATE INDEX "AskObservation_questionClass_occurredAt_idx" ON "AskObservation"("questionClass", "occurredAt");

-- CreateIndex
CREATE INDEX "AskObservation_answerState_occurredAt_idx" ON "AskObservation"("answerState", "occurredAt");

-- CreateIndex
CREATE INDEX "AskObservation_routePath_occurredAt_idx" ON "AskObservation"("routePath", "occurredAt");
